folio-org/ui-requests

- ItemDetail.js
- RequestForm.js
- Requests.js
- UserDetail.js
Execution would crash on the request form if the barcode for a user, or
an item that was currently checked out by a user, who wasn't assigned to
a patron group.
> Fix bug that caused a JS error when certain items or users were selected (UIREQ-30)

- CHANGELOG.md
- ItemDetail.js
- RequestForm.js
- ViewRequest.js
- package.json
Refs [STRIPES-490](https://issues.folio.org/browse/STRIPES-490). Purging local copies of `react-flexbox-grid` in favor of pulling `<Row>` and `<Col>` from `stripes-components`. `react-flexbox-grid` is pegged at v1.1.3 in `stripes-components` because newer versions behave badly and we'd rather not have to manage this dependency all over the place.
> pull Row and Col from stripes-components. Refs STRIPES-490

- test/ui-testing/new_request.js
The Users module was changed to not show any users on initial load. This PR changes the tests to check the 'Active' filter to ensure that a list of users is fetched and displayed.
> UIU-424: Updated tests to handle empty users list onload

- CHANGELOG.md
- RequestForm.js
- translations/en.json
Now that table headers may be i18n'ed, they must be referred to by their
keys, which are constant, rather than their values, which will change
with each translation.
Fixes UIREQ-76
> pass keys, not values, to MCL.

- translations/en.json
This key is used by SearchAndSort and is required for some tests that
inspect the value to be sure the number of requests changes as they are
processed. Full translation will be handled later.
Refs [UIREQ-69](https://issues.folio.org/browse/UIREQ-69)
> provide resultCount translation

- CHANGELOG.md
- RequestForm.js
RequestForm was not passing the correct prop to ItemDetails in order to display those details on the request-edit pane. 
Refs [UIREQ-55](https://issues.folio.org/browse/UIREQ-55)
> pass full item details to ItemDetails. Refs UIREQ-55

- RequestForm.js
itemRecord and item, plain,
Were both perhaps present in selectedItem.
And itemBarcode contained in selectedItem.
In in selectedItem, item, plain, is expunged, and other eternally present,
Request-New and Request-Edit are all clickable.
Passing tests will be no more an abstraction,
becoming a perpetual possibility
in a world of speculative compilation.
What might have passed and what has passed
point to ui-inventory and ui-requests; it is always my fault.
Bug reports echo in the ticket tracker
To the continuous integration server we do not like
Towards the green line we never see
Into the slack-channel. My fix echoes
thus, in your code.
> re-debug the itemDetails. Refs UIREQ-55

- CHANGELOG.md
- test/ui-testing/new_request.js
The active/inactive users filters are deprecated and will be replaced
with a single "Show inactive users" filter; active users will be
returned in all search/filter results. This update accommodates the new
filters.
Refs [UIU-400](https://issues.folio.org/browse/UIU-400)
> accommodate "show active users" filter

- CHANGELOG.md
- ItemDetail.js
Previous implmentations did not adequately guard against
`instance.contributors[0]` being undefined, which would cause a
low-level error trapped by React and showing a warning that the page
would need to reload to continue.
> handle undefined instance.contributors[0]

- RequestForm.js
- ViewRequest.js
Adds the currently-selected request's item title to the tab/window bar via `document.title`.
Also fixes a bug where the newRequest i18n key was referring to a non-existent string.
> STCOR-226: Add request item's title to doc.title

- CancelRequestDialog.js
After UIREQ-99, learned that `name` will be mandatory and not `description`.
> CancelRequestDialog: Use name instead of description prop for reason

- test/ui-testing/new_request.js
The "Active" checkbox no longer exists so we shouldn't wait for it to be in place before clicking and selecting from the (no longer automatically shown) list of users.
> Tests: Don't look for "active" checkbox when searching for user

- package.json
A fix was made to react-intl-safe-html, bumping the patch version to 1.0.2.  However, ui-requests is targeting "^1.0.10007" which is a padded CI build number version only valid on the npm-folioci registry.  Technically 1.0.10007 would satisfy ^1.0.2 even though its actually a build of 1.0.1.  We should avoid using CI build numbers as dependencies.
> Remove npm-folioci build number from dependencies

- Requests.js
- package.json
The request objects are mostly uniform in shape, but sometimes they can have `proxy` fields. I added an option to explicitly include those fields. 
Related PR https://github.com/folio-org/stripes-util/pull/7
> csv export: ensure to include proxy fields

- CHANGELOG.md
- src/ViewRequest.js
`craftLayerUrl()` assists with `<SearchAndSort>`'s routing, and will be deprecated for any other use (modules should define their own routes, instead of relying on `<SearchAndSort>` to do it for them).
> Copy craftLayerUrl from stripes-components

- src/Requests.js
```
import { FilterGroups } from '@folio/stripes/components';
const { filters2cql } = FilterGroups;
```
didn't work:
`filters2cql` is now exported at the root: https://github.com/folio-org/stripes-components/pull/640
> Fix filters2cql import

- CHANGELOG.md
- package.json
- src/Requests.js
Fixes 
```
WARNING in ./node_modules/@folio/requests/src/Requests.js 104:10-21
"export 'exportToCsv' was not found in '@folio/stripes/util' 
```
for https://issues.folio.org/browse/FOLIO-1547
Includes `v1.4.1` release.
>  Fix exportCsv import

- src/Requests.js
- test/ui-testing/filters.js
[UIREQ-150](https://issues.folio.org/browse/UIREQ-150) prevents the display of any requests unless a query or filter is active. The tests now reflect this.
> handle empty results list in filter tests

- test/ui-testing/new_request.js
For forms to be accessible, they must not return results until a user
clicks a search button. Ergo, click the search button. This didn't 
show up until now because we used to show all requests on the landing 
page, allowing the final test to succeed even though it never submitted
the search query, but as of UIREQ-150, the landing page now loads without
results.
Refs [STCOM-354](https://issues.folio.org/browse/STCOM-354), [UIREQ-150](https://issues.folio.org/browse/UIREQ-150),
> click submit when searching

- CHANGELOG.md
- src/CancelRequestDialog.js
- src/RequestForm.js
- src/Requests.js
- src/UserDetail.js
- src/UserForm.js
- src/ViewRequest.js
According to [UIREQ-135](https://issues.folio.org/browse/UIREQ-135), all strings should be internationalized using the react-intl pattern constructs outlined [here](https://github.com/folio-org/stripes/blob/master/doc/i18n.md)
> UIREQ-135: Use documented react-intl patterns instead of stripes.intl

- test/ui-testing/new_request.js
Don't use the `title` attribute as a hook for tests. `title` is being
removed because it is not meant to be used for accessibility.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
> omit title attribute from test hooks

- CHANGELOG.md
- src/RequestForm.js
- src/Requests.js
- src/ViewRequest.js
Removed the deprecated `actionMenuItems`-prop. Replaced with the `actionMenu`-prop along with custom composed action menu's.
**Issue:** https://issues.folio.org/browse/UIREQ-170
**Note:** This PR needs to be merged into stripes-smart-components before merging this one.
https://github.com/folio-org/stripes-smart-components/pull/350
> UIREQ-170: Remove deprecated actionMenuItems-prop

- CHANGELOG.md
- src/RequestForm.js
- src/Requests.js
Pass the query resource down to `<RequestForm>` so it can access the
query string to lookup the user and item records based on the presence
of `userBarcode` and `itemBarcode`.
Additionally, avoid `setTimeout`. This was in there previously because
redux-form's `props.change` method is async and we needed to let that
propagate first. Thing is, we _have_ the user barcode already, so we
don't actually need to wait for that propagation; we can just pass the
value directly. And now we do.
Fixes [UIREQ-146](https://issues.folio.org/browse/UIREQ-146)
> read query string for user and item barcodes

- src/RequestForm.js
- src/requests.css
- test/bigtest/interactors/new-request.js
- test/bigtest/tests/new-request-test.js
- translations/ui-requests/en.json
According to [STCOM-374](https://issues.folio.org/browse/STCOM-374), it should be possible to cancel creating a new request using pane header dropdown.
* add nesessary action to  `actionMenu` attribute of `Pane` component
* add related tests
> STCOM-374: Implement pane header dropdown on create request page

- CHANGELOG.md
- test/bigtest/interactors/requests.js
MCL recently changed how it uses some ARIA properties and the downstream
tests need to reflect this.
Refs [STRIPES-597](https://issues.folio.org/browse/STRIPES-597), [STCOM-365](https://issues.folio.org/browse/STCOM-365)
> update BigTest interactor for MCL

- CHANGELOG.md
- test/ui-testing/filters.js
- test/ui-testing/new_request.js
Changes to the aria attributes in MCL must be reflected in the
integration tests as well.
Refs [UIREQ-205](https://issues.folio.org/browse/UIREQ-205), [STCOM-365](https://issues.folio.org/browse/STRIPES-365). 
See also folio-org/stripes-components/pull/849
> integration tests must accommodate MCL aria changes

- CHANGELOG.md
- test/bigtest/interactors/requests.js
- test/bigtest/tests/requests-show-all-test.js
It seems to be the case that the application served up by mirage comes in
some sort of virgin state regardless of what URL we pass to
`this.visit()`. Deployed, a URL like `/requests?filter=foo` would cause
the "foo" checkbox to be ticked. Not so when running tests where passing a
fancy URL like
/requests?filters=requestType.Holds%2CrequestType.Pages%2CrequestType.Recalls&sort=Request%20Date
appears to return the same page as passing
/requests
What this means is that we need to use interactors to affect the state
that normally we would expect to inherit through the URL.
Fixes [UIREQ-210](https://issues.folio.org/browse/UIREQ-210)
> make unit tests responsible for setting state

- test/ui-testing/filters.js
folio-org/stripes-components/pull/862 uses `kebabCase()` on checkbox ids
to make sure they are consistently formatted. This helps avoid illegal
values like `foo bar` but it also changed legal values like `Foo-Bar` to
`foo-bar` and that wasn't reflected in the tests. Until now!
Refs [STCOM-476](https://issues.folio.org/browse/STCOM-476)
> checkbox-ids are all lowercase

- src/RequestForm.js
It looks like `holdShelfExpirationDate` is pre populated with a full date and time in some cases. 
This PR skips the `holdShelfExpirationDate` formatting if the full date and time is already present.
> Format holdShelfExpirationDate only when the date is set by the user.

- CHANGELOG.md
- src/RequestForm.js
- translations/ui-requests/en.json
The request form contained untranslated, hard-coded strings.
Fixes [UIREQ-219](https://issues.folio.org/browse/UIREQ-219)
> extract strings for translation

- src/CancelRequestDialog.js
This was totally my fault. While working on UIREQ-232 I tried to cleanup react warnings and refactored ModalFooter but with the wrong `onClick` handler.
https://issues.folio.org/browse/UIREQ-249
> Fix cancelling request. Part of UIREQ-249

- src/Requests.js
https://issues.folio.org/browse/UIREQ-250
Pass translated filter label rather than `<FormattedMessage />`
> UIREQ-250: Fix filter label translation for filter config

- CHANGELOG.md
- src/ItemDetail.js
- src/PositionLink.js
- src/RequestForm.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/request.js
- test/bigtest/tests/new-request-test.js
- translations/ui-requests/en.json
`On Order` items don't have barcodes but we still need to be able to create requests for them when coming from the inventory module. 
https://issues.folio.org/browse/UIREQ-253
> Add ability to create a request without an item barcode. Part of UIREQ-253.

- package.json
- src/Requests.js
- test/bigtest/tests/edit-request-test.js
- test/bigtest/tests/new-request-test.js
When cancelling a new request that was generated from ui-users or
ui-inventory, the `userBarcode` or `itemBarcode` parameters would persist in
the URL, causing that data to pre-populate in future requests. No more.
Refs [UIREQ-244](https://issues.folio.org/browse/UIREQ-244)
> clear query-string when cancelling new request

- CHANGELOG.md
- src/Requests.js
It looks like some additional props were included during duplication. This PR should fix it.
https://issues.folio.org/browse/UIREQ-275
> Fix creating hold request via duplicate option. Part of UIREQ-275.

- CHANGELOG.md
- src/Requests.js
It looks `itemId` was not cleaned up for items without the barcode. This PR should fix it.
https://issues.folio.org/browse/UIREQ-274
> Fix opening correct request item during duplication. Part of  UIREQ-274.

- CHANGELOG.md
- test/ui-testing/filters.js
Some requests with questionable data were removed in CIRCSTORE-129. Now,
the tests based on those requests have been removed as well. Eventually,
we probably _should_ have tests for the filters for different request
types, but those integration tests should live at the platform level.
Refs [CIRCSTORE-129](https://issues.folio.org/browse/CIRCSTORE-129)
> remove tests based on flaky data

- src/Requests.js
- src/ViewRequest.js
- src/asyncValidate.js
It looks like async validation was failing in edit mode because we didn't pass the mutator for `RequestForm` during edit. This PR should fix it. 
https://issues.folio.org/browse/UIREQ-283
> Fix async validation during edit. Part of UIREQ-283

- CHANGELOG.md
- src/RequestForm.js
- src/asyncValidate.js
- test/bigtest/interactors/new-request.js
- test/bigtest/tests/new-request-test.js
This PR removes `onInput` handlers from both item and requester inputs. It also refactors async validation (the previous implementation didn't work correctly in some scenarios).
https://issues.folio.org/browse/UIREQ-280
> Refactor async validation on request form. Part of UIREQ-280

- CHANGELOG.md
- src/Requests.js
https://issues.folio.org/browse/UIREQ-287
https://issues.folio.org/browse/UIREQ-285
> Cleanup item lookup values when layer is closed. Fixes UIREQ-285 and UIREQ-287.

- CHANGELOG.md
- src/constants.js
- translations/ui-requests/en.json
Add the library column to Request CSV in the scope of the [issue](https://issues.folio.org/browse/UIREQ-262)
> UIREQ-262:  Add library column to Request CSV

- CHANGELOG.md
- src/constants.js
- translations/ui-requests/en.json
Add Location Code Column to Request CSV according to [story](https://issues.folio.org/browse/UIREQ-263).
**Response**
**.csv file**
> UIREQ-263: Add Location Code Column to Request CSV

- CHANGELOG.md
- src/ItemDetail.js
https://issues.folio.org/browse/UIREQ-311
> Populate shelving location on request view and edit form. Fixes UIREQ-311.

- src/ViewRequest.js
- hide action details menu on view screen if it is empty
https://issues.folio.org/browse/UIREQ-107
> UIREQ-107 - Requests: View

- src/ViewRequest.js
- src/constants.js
To allow display hold shelf expiration date for closed requests
https://issues.folio.org/browse/UIREQ-323
> UIREQ-323 - Hold shelf expiration date not displaying after request expires (Closed - Pickup expired)

- CHANGELOG.md
- src/routes/RequestsRoute.js
This PR modifies requests query to support searching by requester's id. 
This is needed in order to fix a bug described in https://issues.folio.org/browse/UIU-1370
> Add requesterId to requests query. Part of UIU-1370.

- src/MoveRequestManager.js
This PR adjusts the logic for showing the "Can't move above page" popup. This is based on the findings from @bohdan-suprun in https://issues.folio.org/browse/UIREQ-376 and also the comments from @Baroquem under https://issues.folio.org/browse/UIREQ-320
@Baroquem please let me know if this looks good.
> Fix logic for moving item to paged request. Part of UIREQ-376

- src/UserForm.js
- test/bigtest/interactors/edit-request.js
- test/bigtest/tests/edit-request-test.js
Disallow editing of fulfillment preference when a request is in Open - Awaiting delivery/pickup status
[Related story](https://issues.folio.org/browse/UIREQ-369)
> UIREQ-369: disallow editing fulfillment preference on requests with Awaiting delivery/pickup status

- src/RequestForm.js
https://issues.folio.org/browse/UIREQ-377
##Purpose
The edit page of a request displays like a create page when the request is created on item without barcode.
##Screenshots
Before
https://issues.folio.org/secure/attachment/22940/screenshot-2.png
After
> UIREQ-377: Fix indicator of edit page

- CHANGELOG.md
- src/RequestForm.js
Fix bug with wrong delivery address selected when preference is equal 'hold shelf' and then changed
https://issues.folio.org/browse/UIREQ-380
> UIREQ-380: Fix bug with wrong deliver address in request form

- CHANGELOG.md
- src/RequestForm.js
Deny to save a request if selected patron is blocked.
https://issues.folio.org/browse/UIREQ-394
> UIREQ-394 - Blocked patron can successfully place a Request

- CHANGELOG.md
- src/RequestForm.js
I'm not sure why block would be undefined in some cases. This PR is just a quick fix so the request can be created. We may need to revisit the `getPatronBlocks`. 
https://issues.folio.org/browse/UIREQ-396
> UIREQ-396: Fix reference to userId via block

- CHANGELOG.md
- src/RequestForm.js
- src/UserForm.js
Show the Fulfillment preference menu with Hold shelf selected and the menu for selecting the service point for pickup when user logs in from user(not diku_admin) and trying to duplicate the request
https://issues.folio.org/browse/UIREQ-385
> UIREQ-385: Fix bug with wrong menus when duplicating request

- src/RequestForm.js
The request details pane was inadvertently duplicated during a botched
merge. Cate found the symptoms in the UI, @hjiebsco found the error in
the code, and I'm just doing the clean up.
Fixes [UIREQ-404](https://issues.folio.org/browse/UIREQ-404)
> UIREQ-404 removed duplicate requester details

- src/ItemDetail.js
Brainfart: in the request-details pane I only updated the width 
of the columns in rows 1 and 2; forgot about row 3. Whoops.
[UIREQ-366](https://issues.folio.org/browse/UIREQ-366)
> UIREQ-366 correctly align columns

- translations/ui-requests/en.json
The label should be "Effective call number string", not "Call number".
[UIREQ-366](https://issues.folio.org/browse/UIREQ-366)
> UIREQ-366 use correct label

- CHANGELOG.md
- src/routes/RequestsRoute.js
Change condition to make `Hold Shelf clearance report` active when there are items matching the logged in users service point and inactive (greyed out) when there are no items matching the logged in users service point, **not depending** from search/filtered results.
https://issues.folio.org/browse/UIREQ-395
> UIREQ-395: Change conditions for disabling link

- CHANGELOG.md
- src/routes/RequestsRoute.js
Add 'Load more' button at the end of the results list. [Story](https://issues.folio.org/browse/UIREQ-427).
> UIREQ-427: Add 'Load more' button at the end of the results list

- CHANGELOG.md
- package.json
Update the optional-dep on plugin-find-user to one that uses a
compatible version of `@folio/stripes`.
> upgrade plugin-find-user to v2.0.0

- CHANGELOG.md
- src/ItemDetail.js
- src/routes/RequestsRoute.js
- test/bigtest/interactors/edit-request.js
- test/bigtest/interactors/view-request.js
- test/bigtest/network/factories/request.js
- test/bigtest/tests/edit-request-test.js
- test/bigtest/tests/view-request-test.js
Fix display of the request count on the item in the view and edit mode. Story [UIREQ-433](https://issues.folio.org/browse/UIREQ-433).
- fixed a bug from PR #501 that accidentally removed the request attributes from the object returned by addRequestFields;
- added tests for 'Requests on item' field.
**View mode**
**Edit mode**
> UIREQ-433: Fix display of the request count on item

- CHANGELOG.md
- src/ViewRequest.js
- src/routes/RequestsRoute.js
- test/bigtest/interactors/header-dropdown-menu.js
- test/bigtest/tests/all-requests-test.js
Paneheader Actions updates
- Replace `New` button into `Actions` dropdown menu
- Remove `Edit` icon 
https://issues.folio.org/browse/UIREQ-415
**Before**
**After**
> UIREQ-415: Paneheader Actions updates

- translations/ui-requests/en.json
Change validation message for select user field
https://issues.folio.org/browse/UIREQ-371
> UIREQ-371 - No warning or error message when creating a request for user with no barcode

- CHANGELOG.md
- src/utils.js
https://issues.folio.org/browse/UIREQ-456
Copying the proxyUserId when duplicating a request that has a proxy user causes an error when trying to save the new request.
> UIREQ-456: Omit proxyUserId from duplicated properties

- CHANGELOG.md
- src/RequestForm.js
https://issues.folio.org/browse/UIREQ-455
This PR fixes an issue when creating new requests for proxy users: the pickup service point was not being populated for sponsors who had a specified service point preference.
> UIREQ-455: Set correct service point default for proxy sponsors

- CHANGELOG.md
- src/RequestForm.js
- src/constants.js
- src/utils.js
- test/bigtest/interactors/new-request.js
- test/bigtest/tests/new-request-test.js
- translations/ui-requests/en.json
Prevent requests for items with the status `Withdrawn`. Story [UIREQ-390](https://issues.folio.org/browse/UIREQ-390).
Since the prevention of requests for items with the status `Declared lost` and `Withdrawn` is performed in a similar way, the code was refactored to use one functionality in both cases.
> UIREQ-390: Prevent requests for Withdrawn items

- CHANGELOG.md
- src/MoveRequestDialog.js
- translations/ui-requests/en.json
The label in question had a static placeholder in the translation file for the
item title.  I replaced this with a variable, and passed in the item title from the
modal render function.  Once this change propagates out to all the translation
files, they should start showing the item title in the modal.
Refs: https://issues.folio.org/browse/UIREQ-304
> UIREQ-304:  Missing Instance title from the Moving Request popup

- translations/ui-requests/en_GB.json
- translations/ui-requests/en_SE.json
- translations/ui-requests/en_US.json
FOLIO-2630 is preventing changes from propagating to `en_*` locales;
this does that manually for the changes requested in UIREQ-304 (#583).
Refs [UIREQ-304](https://issues.folio.org/browse/UIREQ-304), [FOLIO-2630](https://issues.folio.org/browse/FOLIO-2630)
> UIREQ-304 force update of en_* locales

- CHANGELOG.md
- package.json
Increment `@folio/plugin-find-user` version to `^3` for
compatibility with `@folio/stripes` `4.0`.
> increment plugin-find-instance to v3

- CHANGELOG.md
- test/bigtest/interactors/view-request.js
- test/bigtest/tests/view-request-test.js
- translations/ui-requests/en.json
All needed functionality already provided in [PR](https://github.com/folio-org/ui-requests/pull/590) 
Also here just add test for 'assign / unassign' button
[UIREQ-458](https://issues.folio.org/browse/UIREQ-458)
> UIREQ-458: Request staff notes: Assign/Unassign Notes

- CHANGELOG.md
- src/routes/RequestsRoute.js
Use `==` instead of `=` for more efficient queries.
Refs [PERF-62](https://issues.folio.org/browse/PERF-62)
> PERF-62 use == for more efficient queries

- package.json
Add missing permission for creating request through `duplicate`
https://issues.folio.org/browse/UIREQ-486
> UIREQ-486: add permission

- CHANGELOG.md
- package.json
The tag-management component would display but throw errors because
there was no way to assign tag-related permissions in the UI. The
interaction between tag-CRUD permissions and entity-CRUD permissions can
be confusing and the `<Tags>` component does not, at present, handle
discrepancies between them.
Refs [UITAG-29](https://issues.folio.org/browse/UITAG-29)
> UITAG-29 provide tag-related permissions

- CHANGELOG.md
- src/ItemDetail.js
- src/PositionLink.js
The support for item ids was already there so this turned out to be a quick fix.
https://issues.folio.org/browse/UIREQ-484
> UIREQ-484: Use item id instead of barcode for links on request details screen.

- CHANGELOG.md
- src/RequestForm.js
- src/UserDetail.js
- src/UserForm.js
- src/views/RequestQueueView.js
https://issues.folio.org/browse/UIREQ-499
In several places in the app, a requester's patron group was being shown using the group description rather than the actual group name (the 'group' value, confusingly). Now we'll use the group name, making all those nondescript groups a little more visible.
> UIREQ-499: Use patron group name instead of description in displays

- CHANGELOG.md
- package.json
- src/utils.js
Values passed to `react-to-print` need to be escaped because of the way
it generates its document under the hood. Without escaping, if we passed
a value like `something<bad>very bad`, this would cause React to blow up
when slips were generated with an error like
```
ERROR:Failed to execute 'createElement' on 'Document':The tag name
provided ('bad') is not a valid name.
```
Refs [UIREQ-510](https://issues.folio.org/browse/UIREQ-510)
> UIREQ-510 html-encode strings for react-to-print

- CHANGELOG.md
- package.json
- src/components/PrintButton/PrintButton.js
- src/routes/RequestsRoute.js
- translations/ui-requests/en.json
For a very large number of slips it was not clear if the print process has started or not. This PR adds a callout and closes the menu after the print button is clicked.
https://issues.folio.org/browse/UIREQ-508
> UIREQ-508: Add feedback after print button is clicked

- CHANGELOG.md
- package.json
- src/routes/RequestsRoute.js
- src/views/RequestQueueView.js
In the spirit of sparing *some horizontal space... This almost knocked off a whole column width from the example data...
> STRIPES-693 Apply columnwidths API to MCL

- CHANGELOG.md
- package.json
Apps and plugins must depend on the same versions of peer dependencies.
Refs [UIREQ-535](https://issues.folio.org/browse/UIREQ-535)
> UIREQ-535 update plugins for stripes v5 compat

- CHANGELOG.md
- src/utils.js
When new request is created as duplicate of existing request, then `HoldShelfExpirationDate` field should NOT be duplicated.
https://issues.folio.org/browse/UIREQ-532
> UIREQ-532: Omit HoldShelfExpirationDate field in duplicated request

- CHANGELOG.md
- src/components/RequestsFilters/RequestsFiltersConfig.js
https://issues.folio.org/browse/UIREQ-542
It looks like due to this change:
https://github.com/folio-org/stripes-components/pull/1368
the searching by tags stopped working because `tags.tagList` only works with `=`.
> UIREQ-542: Fix search by tags

- CHANGELOG.md
- src/MoveRequestDialog.css
- src/MoveRequestDialog.js
https://issues.folio.org/browse/UIREQ-541
Since the modal became scrollable after increasing the limit, it had to change the styles to be able to see all items in it.
> UIREQ-541: Increase limit to display all items in Move request modal

- CHANGELOG.md
- src/MoveRequestDialog.css
- src/MoveRequestDialog.js
https://issues.folio.org/browse/UIREQ-552
This PR fixes a bug that came up after #661 when the modal window styles were changed to implement scrolling.
> UIREQ-552: Fix the non-responsive design of Move request modal

- test/bigtest/tests/new-request-test.js
Failing tests in #668 appear to be timing related, failing to await the
display of the request-details pane (or running out of time before it
displays). Wish I knew why this started showing up all of a sudden, but
here we are.
> await request details pane

- src/PatronBlockModal.js
- change blocks order
- show only one manual block on the modal
https://issues.folio.org/browse/UIREQ-496
> UIREQ-496 - Patron block modal for Requesting should display up to 3 blocks, with Automated Patron Blocks on top of Manual Patron Blocks

- CHANGELOG.md
- src/ViewRequest.js
- src/routes/RequestsRoute.js
- test/bigtest/tests/new-request-test.js
- test/bigtest/tests/view-request-test.js
https://issues.folio.org/browse/UIREQ-553
Allow for duplicating a closed request.
> UIREQ-553: Allow for duplicating a closed request

- CHANGELOG.md
- src/MoveRequestDialog.js
- src/utils.js
https://issues.folio.org/browse/UIREQ-558
The problem for which this PR is addressed has the same origin as the problem described in [#974](https://github.com/folio-org/ui-users/pull/974). And the solution is the same.
The only difference is that chunks of 40 are used to retrieve open requests against items.
> UIREQ-558: Retrieve requests to items in chunks

- CHANGELOG.md
- src/RequestForm.js
- src/ViewRequest.js
- test/bigtest/interactors/edit-request.js
- test/bigtest/interactors/new-request.js
- test/bigtest/interactors/view-request.js
- test/bigtest/tests/edit-request-test.js
- test/bigtest/tests/new-request-test.js
- test/bigtest/tests/view-request-test.js
- translations/ui-requests/en.json
https://issues.folio.org/browse/UIREQ-530
Add the `Patron comments` field to the `View`, `New`, and `Edit` request pages. Additionally, on the `Edit` page this field should be uneditable.
> UIREQ-530: Add `Patron comments` field to request

- CHANGELOG.md
- src/utils.js
- test/bigtest/tests/utils-test.js
Show `lastCheckedInDateTime` token for staff slips in locale format and date/time instead of UTC (Zulu time)
https://issues.folio.org/browse/UIREQ-495
**Before**
**After**
> UIREQ-495: Show `lastCheckedInDateTime` token for staff slips in locale format and date/time

- CHANGELOG.md
- src/utils.js
- test/bigtest/tests/utils-test.js
Fix barcode displaying for print slips.
https://issues.folio.org/browse/UIREQ-570
> UIREQ-570 - Barcode image does not render in print slips

- CHANGELOG.md
- src/RequestForm.js
- src/constants.js
- src/utils.js
- test/bigtest/tests/new-request-test.js
https://issues.folio.org/browse/UIREQ-393
Prevent requests of any type from being made on items with `intellectual item`, `in process (non-requestable)`, `long missing`, `unavailable`, and `unknown` statuses.
> UIREQ-393: Prevent requests for 5 new item statuses

- CHANGELOG.md
- src/ViewRequest.js
- src/routes/RequestsRoute.js
- test/bigtest/network/config.js
- test/bigtest/tests/view-request-test.js
https://issues.folio.org/browse/UIREQ-543
Add the ability to get the canceled request data immediately after the request cancellation event (without refreshing the page) to build an up-to-date `Hold shelf clearance report`.
> UIREQ-543: Fix canceled request display in Hold shelf clearance report

- CHANGELOG.md
- test/bigtest/tests/new-request-test.js
https://issues.folio.org/browse/UIREQ-581
The main work was done at BE ([#823](https://github.com/folio-org/mod-circulation/pull/823)).
On FE it was necessary to check the correctness of its display and implement a test case.
> UIREQ-581: Allow requests for Restricted items

- CHANGELOG.md
- src/RequestForm.js
- src/components/ErrorModal.js
- src/utils.js
https://issues.folio.org/browse/UIREQ-587
Parsing `errorMessage` as a string inside `ErrorModal` will throw an error if `errorMessage` is a React element.
errorMessage: PropTypes.oneOfType([
PropTypes.string,
PropTypes.element,
]).isRequired,
This PR addresses this issue by moving the parsing out of `ErrorModal`.
> UIREQ-587: Fix display of ErrorModal content

- CHANGELOG.md
- package.json
* Update `react-intl-safe-html` to `v3` for compatibility with
`react-intl` `v5`/`@folio/stripes` `v6`.
* Update `@folio/plugin-find-user` to `v3` for compatibility with
`@folio/stripes` `v6`.
> use compatible versions of shared modules

- CHANGELOG.md
- src/RequestForm.js
Choose correct service point when patron is changed in duplicate mode.
https://issues.folio.org/browse/UIREQ-595
> UIREQ-595: Choose correct service point when patron is changed in duplicate mode

- CHANGELOG.md
- package.json
The only breaking change in `circulation` `10.0` was the removal of the
`override-check-out-by-barcode` which is not used here, hence continuing
to support `9.0`.
Refs [UIREQ-600](https://issues.folio.org/browse/UIREQ-600)
> UIREQ-600 also support circulation 10.0

- CHANGELOG.md
- package.json
- src/routes/RequestsRoute.js
Include ISBN search. The `itemIsbn` index is actually a part of
mod-circulation-storage, though it is accessed here via the
business-logic module that sits on top of it, mod-circulation, thus
bumping the minimum `circulation` okapi-index to `10.0`, the lowest
version that is guaranteed to supply that index.
Refs [UIREQ-354](https://issues.folio.org/browse/UIREQ-354)
> UIREQ-354 provide search by isbn

- CHANGELOG.md
- src/components/PrintButton/PrintButton.js
- src/routes/RequestsRoute.js
PropTypes have drifted out of sync causing numerous spurious console
warnings.
It is not obvious to me how to correct this one from where [`RequestsRoute` calls SearchAndSort](https://github.com/folio-org/ui-requests/blob/bc47dfcd347bff3aa395b7f2d340a09e722b2b06/src/routes/RequestsRoute.js#L894):
```
Warning: Failed prop type: Invalid prop `editRecordComponent` of type `object` supplied to `SearchAndSort`, expected `function`.
```
There's no console warning in [ui-inventory](https://github.com/folio-org/ui-inventory/blob/ed445992b4ca3595a5440c3a85c468113f7d611e/src/components/InstancesList/InstancesList.js#L654). What's special about ui-requests? 🤔 
Refs [UIREQ-604](https://issues.folio.org/browse/UIREQ-604)
> UIREQ-604 avoid proptypes errors at all costs

- CHANGELOG.md
- src/ItemDetail.js
- src/RequestForm.js
- src/components/ReferredRecord/ReferredRecord.js
- src/routes/RequestsRoute.js
- src/views/RequestQueueView.js
`<FormattedDate>` and `<FormattedTime>` do not handle some timestamp
formats correctly in some versions of Safari. Pass-through components
that refort such values as necessary are available in
`stripes-components` and are used here to allow request-related data to
be correctly display on iOS tablets and phones.
Refs [UIREQ-528](https://issues.folio.org/browse/UIREQ-528)
> UIREQ-528 consume date/time i18n components via stripes

- CHANGELOG.md
- src/asyncValidate.js
During async-validation of requests, use an exact-match query for the
item barcode. This is faster and more efficient.
Refs [UIREQ-602](https://issues.folio.org/browse/UIREQ-602)
> UIREQ-602 use exact-match query for item validation

- CHANGELOG.md
- package.json
There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.
**Do not merge. We have several associated pull request and we need merge them at the same time.**
**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module
https://issues.folio.org/browse/UIREQ-608
> UIREQ-608: Update circulation interface dependency to support v11

- CHANGELOG.md
- package.json
Provide the missing permission,
`circulation-storage.request-preferences.collection.get`, to the
request-create and request-edit psets in order to allow for the
retrieval of users' preferred pickup points.
Refs [UIREQ-628](https://issues.folio.org/browse/UIREQ-628)
> UIREQ-628 provide request-preferences permission

- CHANGELOG.md
- src/constants.js
- src/utils.js
- src/utils.test.js
When cloning an existing request, if the original has been cancelled, do
not include the cancellation-related fields in the clone.
Refs [UIREQ-627](https://issues.folio.org/browse/UIREQ-627)
> UIREQ-627 omit cancellation details in duplicated requests

- CHANGELOG.md
- src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-629
This is a similar pattern to what has been done with `Print pick slips for API` option.
> UIREQ-629: Disable hold shelf clearance report when a request for hold shelf data is pending.

- package.json
Depend on the new inventory interface version for optimistic locking
in addition to the old interface version.
This modules uses GET for instance, holdings and item, but doesn't
PUT them. Therefore no code change is needed to support the
_version property in these records that are needed for
optimistic locking.
> UIREQ-646: Add interface version for inventory optimistic locking

- CHANGELOG.md
- src/UserDetail.js
- src/utils.js
Display missing requester fields as blanks
https://issues.folio.org/browse/UIREQ-672
> UIREQ-672 When newly added patron is deleted after making and canceling request, requests page is unstable

- CHANGELOG.md
- src/ViewRequest.js
Components in `@folio/stripes-*` should be imported via their public
paths in `@folio/stripes` instead of directly.
Fixes [UIREQ-609](https://issues.folio.org/browse/UIREQ-609)
> UIREQ-609 import via @folio/stripes/core

- package.json
- test/jest/babel.config.js
Don't maintain a local copy; import the common config file from
`@folio/stripes-cli`. This has the added benefit of silencing the 10
billion "The "loose" option must be the same ..." messages that show up
when running Jest tests.
Refs [UIREQ-678](https://issues.folio.org/browse/UIREQ-678), [STCLI-182](https://issues.folio.org/browse/STCLI-182)
> UIREQ-678 use shared babel config

- src/ViewRequest.js
Resolve the following warning: 
```
$ yarn lint
yarn run v1.22.11
$ eslint .
/Users/zburke/projects/folio-org/ui-requests/src/ViewRequest.js
22:8   error  '/Users/zburke/projects/folio-org/ui-requests/node_modules/@folio/stripes/core/index.js' imported multiple times  import/no-duplicates
42:30  error  '/Users/zburke/projects/folio-org/ui-requests/node_modules/@folio/stripes/core/index.js' imported multiple times  import/no-duplicates
✖ 2 problems (2 errors, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
```
> lint: only one stripes/core import

- CHANGELOG.md
- src/ViewRequest.js
- src/ViewRequest.test.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesCore.mock.js
Closed title-level request should not be able to be duplicated when TLR is disabled in settings.
Also if we have no any action for request,`Actions` button should not apear.
We just need to check the level of `Closed` request and TLR feature state in settings.
If there are no buttons in action menu, the `Actions` button is not rendered by default.
https://issues.folio.org/browse/UIREQ-691
> UIREQ-691: Closed TLR should not be able to be duplicated when TLR is disabled

- CHANGELOG.md
- src/utils.js
As a staff user
I want to see the patron's preferred first name in the name display in the Checkout and Request UI
so that I might address the patron properly.
condition, included preferredFirstName has been added to the getFullName function
https://issues.folio.org/browse/UIREQ-605
> UIREQ-605 - Add preferred name to Requests UI

- CHANGELOG.md
- src/ItemsDialog.js
- src/ItemsDialog.test.js
- test/jest/__mock__/stripesComponents.mock.js
After the "Select item" window appears, the size of the Request information changes
Wrapped `Pane` in `Paneset`
https://issues.folio.org/browse/UIREQ-690
> UIREQ-690: After the "Select item" window appears, the size of the Request information changes

- src/routes/RequestsRoute.js
Fix wrong query parameters type.
We should pass object with `query` parameter instead of `string`
> fix tlr issues

- CHANGELOG.md
- package.json
- test/bigtest/interactors/sortable-list.js
Older versions of `react-beautiful-dnd` drag in an unsupported version
of `core-js` that causes a build warning. Update to a current version
and adjust the `sortable-list` interactor to reflect changes to the
attributes on the list-wrapper element.
Refs [UIREQ-698](https://issues.folio.org/browse/UIREQ-698), [STRIPES-675](https://issues.folio.org/browse/STRIPES-675)
> UIREQ-698 upgrade to current react-beautiful-dnd

- CHANGELOG.md
- src/PositionLink.js
- src/RequestForm.js
- src/ViewRequest.js
- src/index.js
- src/routes/RequestQueueRoute.js
- src/routes/urls.js
- src/views/RequestQueueView.js
- src/views/RequestQueueView.test.js
- src/views/components/ItemLink.js
- test/bigtest/network/config.js
- test/bigtest/tests/request-queue-test.js
Migrate requests queue/reorder page on new end-points
Depends on is TLR swithced on or off we should pass instanceId or itemId in path and handle this inside component. Depends on what was passed, we should do fetch requests from correct endpoints, and send back reordered queue on correct end-point.
When we send back reorderd queue we should send full queue from first to last position, according this fact `notYetFilledRequests` and `inProgressRequests` collections was extracted one layer highe.
As we now have two separate accordions with requests but still one queue, reorder approach was a little bit changed.
Additionaly I removed `sort` of requests by position because new queue end-points return already sorted array.
Also fixed some small issues which can lead to errors or bugs. …
> UIREQ-695: Migrate requests queue/reorder page on new end-points

- test/bigtest/tests/all-requests-test.js
Tests for requests fail because of default timeout(2000 milliseconds).
Increase timeout for requests tests
> increase failed tests timeout

- CHANGELOG.md
- src/RequestForm.js
- src/ViewRequest.js
- src/views/components/ItemLink.js
- src/views/components/ItemLink.test.js
Change render dependency for item link and information from `requestLevel` to `item`.
Additionaly I droped duplicated records in `CHANGELOG`. They probably was added in scope of merge of master and migration branches in feature branch.
Also added `unset` of two fields, which by different reasons can present in `requestData` when they should not.
https://issues.folio.org/browse/UIREQ-704
> UIREQ-704: Change render dependency for item link and information

- CHANGELOG.md
- src/routes/RequestQueueRoute.js
- src/views/RequestQueueView.js
Disable validation on reordering for `Page` requests for `TLR` feature.
We just need to check is our TLR feature enabled.
Also we can remove validation on not yet filled request, because now we have two accordions for requests with different statuses. At the second accordion, where we can reorder queue, will not be requests with status differ than `Open - Not yet filled`.
https://issues.folio.org/browse/UIREQ-706
> UIREQ-706: Disable validation on reordering for `Page` requests for `TLR` feature

- CHANGELOG.md
- src/PositionLink.js
- src/routes/RequestsRoute.js
- translations/ui-requests/en.json
Add all required attributes for the `position` field in request info
End-points for geting requests was changed because our BE team says that using of `request-storage` is not correct way.
Removed multiple `settings` parsing, now all necessary fields stored in the `state`.
https://issues.folio.org/browse/UIREQ-707
> UIREQ-707: Add all required attributes for the `position` field in request info

- CHANGELOG.md
- package.json
Support okapi interfaces `circulation` `13.0`
* Was changed API associated with request queue.
https://issues.folio.org/browse/UIREQ-717
> UIREQ-717: Upgrade circulation to 13.0

- CHANGELOG.md
- src/RequestForm.js
- src/ViewRequest.js
Fix unnecessary add of the `numberOfNotYetFilledRequests` field to the request data.
https://issues.folio.org/browse/UIREQ-726
> UIREQ-726: Fix unnecessary add of the `numberOfNotYetFilledRequests` field

- CHANGELOG.md
- src/PositionLink.js
- src/RequestForm.js
- src/ViewRequest.js
- src/constants.js
The user should be redirected at the same page if click on the "view requests in queue" link from `request detail` page and from `edit` page.
Also if request has one of `closed` status we should display `dash` in queue field.
On `edit` page we didn't pass `isTlrEnabled` in `PositionLink` component. Thats the reason why we always was redirected on `item` queue insead of `instance`.
I tried to pass `parrentResources` into the `RequestForm` component from `ViewRequest` to get TLR feature status directly in `RequestForm`, but this broke some logic.
So I passed just `isTlrEnabled` flag from `ViewRequest` thru `RequestForm` into `PositionLink` component.
https://issues.folio.org/browse/UIREQ-727
> UIREQ-727: Fix `view requests in queue` link behaviour

- CHANGELOG.md
- src/ItemDetail.js
- src/routes/RequestsRoute.js
Add link for `Requests on item` field if level of request is `Title`.
We should not rely on request `level` because `title` requests in some moment can have item in their record.
According to discussing with PO, we should display `0` if have no requests on item (such case can be for closed requests), and this value should not be a `link`.
https://issues.folio.org/browse/UIREQ-730
> UIREQ-730: Add link for `Requests on item` field if level of request is `Title`

- CHANGELOG.md
- package.json
Add `circulation.requests.queue.collection.get` as subpermission for `Requests: Reorder queue` permission.
https://issues.folio.org/browse/UIREQ-734
> UIREQ-734: add permission `circulation.requests.queue.collection.get`

- CHANGELOG.md
- package.json
- src/CancelRequestDialog.js
- src/ChooseRequestTypeDialog.js
- src/RequestForm.js
- test/jest/__mock__/index.js
- test/jest/__mock__/reactIntlSafeHtml.mock.js
Everything `SafeHTMLMessage` can do `FormattedMessage` can do to without
an extra import.
Refs [UIREQ-610](https://issues.folio.org/browse/UIREQ-610), [STRIPES-754](https://issues.folio.org/browse/STRIPES-754)
> UIREQ-610 replace SafeHTMLMessage with FormattedMessage

- src/RequestForm.test.js
- src/ViewRequest.test.js
- src/routes/RequestsRoute.test.js
- test/bigtest/network/factories/request.js
- test/bigtest/tests/edit-request-test.js
Previously we skipped few Jest/RTL test suits, and also one bigtest. This PR aimed to resolve issues with tests.
Looks like problems with Jest/RTL was temporary and now they are not reproducible. As for bigtest: I just moved `personal` user data to the correct place in the mocks, the same where it locate in real responces.
I am not sure should we add something to changelog in this PR.
https://issues.folio.org/browse/UIREQ-745
> UIREQ-745: restore skipped tests

- CHANGELOG.md
- src/constants.js
- src/routes/RequestsRoute.js
There was mismatching between number of requests on `request detail` page and reorderable accordion on the `reorder queue` page.
Again we can see here the problem with query limits witch is `10` by default. 
https://issues.folio.org/browse/UIREQ-754
> UIREQ-754: fix request details `# items` to show correct number

- CHANGELOG.md
- src/PositionLink.js
- src/RequestForm.js
- src/ViewRequest.js
- src/routes/RequestsRoute.js
- src/routes/utils.js
- src/routes/utils.test.js
Ensure Request details # (# requests) shows correct data.
After changes that was made in [UIREQ-728](https://issues.folio.org/browse/UIREQ-728) all `Page` requests situated in non-reorderable accordion. As discussed with PO, our `# reuqests` should represent number of reorderable requests.
I added coresponding filter and also renamed `numberOfNotYetFilledRequests` to `numberOfReorderableRequests` because it's no more match with what exact this number mean.
https://issues.folio.org/browse/UIREQ-757
> UIREQ-757: changes requests filter logic to  shows correct number in `# requests`

- CHANGELOG.md
- src/routes/RequestsRoute.js
The `position` field is numeric, so that needs to be configured in the
`sortMap` argument passed to `makeQueryParam`.
Refs [UIREQ-750](https://issues.folio.org/browse/UIREQ-750)
> UIREQ-750 sort queue position numerically

- CHANGELOG.md
- src/ItemDetail.js
- src/RequestForm.test.js
- src/ViewRequest.js
- src/routes/RequestsRoute.test.js
Add Move request to Action list when item is attached to title level request for fulfillment.
Instead of request level, we should check item presence and then show or hide `move` button.
Fixed jest tests because they didn't run locally.
https://issues.folio.org/browse/UIREQ-767
> UIREQ-767: add `move` action for title-level requests with attached item

- CHANGELOG.md
- src/ItemDetail.js
- src/ItemDetail.test.js
- src/components/TitleInformation/TitleInformation.js
- src/components/TitleInformation/TitleInformation.test.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesSmartComponents.mock.js
Disable item and instance links in request detail when hardcoded UID is present.
This is a continuation of issue described in [this PR](https://github.com/folio-org/ui-requests/pull/928).
https://issues.folio.org/browse/UIREQ-784
> UIREQ-784: disable item and instance links in request detail when hardcoded UUID is present

- CHANGELOG.md
- src/ItemsDialog.js
- src/ItemsDialog.test.js
- src/constants.js
Filter the items list on "move request" action from items with non-requestable statuses.
When we have `skippedItemId` it means that we in `move request` process, so we should filter our list from items with non-requestable statuses. 
https://issues.folio.org/browse/UIREQ-787
> UIREQ-787: filter the items list on `move request` action from items with non-requestable statuses

- CHANGELOG.md
- src/RequestForm.js
Fix validation issue of item barcode field
[UIREQ-694](https://issues.folio.org/browse/UIREQ-694)
**BEFORE**
**AFTER**
> UIREQ-694: The message "Item with this barcode does not exist" should appear whenever the user tries to enter a invalid item barcode

- CHANGELOG.md
- src/ViewRequest.js
- src/constants.js
- translations/ui-requests/en.json
We already created [tech debt](https://issues.folio.org/browse/UIREQ-789) about localization for errors within request closing.
Improve of error handling on closing already closed request.
https://issues.folio.org/browse/UIREQ-344
before:
after:
> UIREQ-344: deleting already-deleted request causes ungraceful error

- CHANGELOG.md
- src/RequestForm.js
- src/routes/RequestsRoute.js
Eslint fixed paddings, so it looks like a lot of changes, but in real only two strings was changed.
Without whitespaces: https://github.com/folio-org/ui-requests/pull/936/files?w=1
Fix the number of title-level requests on request details and within creation of new title-level request.
The easiest way to get only title-level request is not working as expected. Relying on this number we calculate the number of reorderable requests. So had to just filter requests on title from requests with the same title but with `Item requestLevel`.
https://issues.folio.org/browse/UIREQ-790
> UIREQ-790: fix the number of title-level requests

- CHANGELOG.md
- src/ViewRequest.js
A closed Request should not be edited. Hence disable the tags Icon Button on closed request.
Issue: https://issues.folio.org/browse/UIREQ-794
Closed Request - Tags Icon Button disabled
Open Request - Tags Icon Button remain enabled
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> UIREQ-794: Сannot add tags to record in the Requests app

- CHANGELOG.md
- src/CancelRequestDialog.js
- src/routes/RequestsRoute.js
The `cancellation-reasons` request lacked a `limit` clause, applying a
de facto limit of only ten entries. Providing an explicit `limit`
retrieves up to 10000.
Refs [UIREQ-795](https://issues.folio.org/browse/UIREQ-795)
> UIREQ-795 retrieve up to MAX_RECORDS cancellation-reasons

- CHANGELOG.md
- src/PositionLink.js
- src/components/RequestFormShortcutsWrapper/RequestsFormShortcutsWrapper.test.js
- src/components/RequestsRouteShortcutsWrapper/RequestsRouteShortcutsWrapper.test.js
- src/components/ViewRequestShortcutsWrapper/ViewRequestShortcutsWrapper.test.js
Components are incorrectly imported directly from stripes-* packages
https://issues.folio.org/browse/UIREQ-792
We have imports "@folio/stripes-" but all of them associated with tests
> UIREQ-792: Components are incorrectly imported directly from stripes-* packages

- CHANGELOG.md
- package.json
Add version `12.0` to the list of supported `inventory` interface versions.
`DELETE /inventory/instances` and `DELETE /inventory/items` have been deleting all records.
MODINV-731 changed them to delete records by CQL, this requires a major interface version bump.
ui-requests doesn't use these two `DELETE` APIs therefore no code change is needed.
> UIREQ-819: Support inventory 12.0 in okapiInterfaces

- CHANGELOG.md
- src/RequestForm.js
When a user deselects the "Create title level request" checkbox and then clicks the "Save and close" button we had an error.
The issue happened because we have a redundant API call without "instanceId" value. 
In this case, we will not do the server request because it is not necessary.
https://issues.folio.org/browse/UIREQ-826
> UIREQ-826: TLR: when changing from title request to item request, form can't "save & close"

- src/RequestForm.js
- src/utils.js
- src/utils.test.js
- test/bigtest/interactors/new-request.js
- test/bigtest/tests/new-request-test.js
After selecting the request type onBlur event was executed. After that validation for some fields was called. It made reset of request type.
I have deleted `validateOnBlur=true` property of Form. Instead of that I have implemented field level validation.
Also, in the scope of this PR I have moved some methods of RequestForm component to utils to make testing of the component easier in the future.
[UIREQ-824](https://issues.folio.org/browse/UIREQ-824)
> UIREQ-824: TLR: request type reverts to page when placing request

- CHANGELOG.md
- src/RequestForm.js
- src/RequestForm.test.js
User is not able to select Fulfillment preference correctly due to incorrect migration from Redux Form to React Final Form. 
Also, the same issue with Delivery address selector.
[UIREQ-837](https://issues.folio.org/browse/UIREQ-837)
> UIREQ-837: Cannot submit a request with fulfillment preference = Delivery

- CHANGELOG.md
- src/RequestForm.js
When the user tries to create a request with `itemId` but **without** `item.barcode` we have a validation error for `item barcode` field which says that the field is empty. But we should not have that error. 
The issue appeared after migration from Redux Form to React Final Form.
I have disabled validation of `item barcode` field if it is empty and `itemId` is presented (the same functionality as on Morning Glory).
[UIREQ-840](https://issues.folio.org/browse/UIREQ-840)
> UIREQ-840: Cannot save item request from On Order item, because need a barcode

- CHANGELOG.md
- src/RequestForm.js
After migration from Redux Form to React Final Form we were not able to create requests if a user doesn't have a barcode. 
I changed the validation which should let us create a request if the user was selected and a user barcode field is empty or/and a user doesn't have a barcode.
We have the same behavior on Morning Glory.
Also, removed magic strings 😇 
[UIREQ-849](https://issues.folio.org/browse/UIREQ-849)
> UIREQ-849: Cannot submit a request with a user without barcode

- CHANGELOG.md
- package.json
Update `request-storage` interface version due to braking changes in `mod-circulation-storage`
[UIREQ-863](https://issues.folio.org/browse/UIREQ-863)
> UIREQ-863: Update versions of interfaces request-storage

- CHANGELOG.md
- package.json
Correctly locate `babel-plugin-module-resolver` in dev-deps since it is not a runtime dependency, and update it to v5 in order to avoid CVE-2022-46175.
Refs [UIREQ-897](https://issues.folio.org/browse/UIREQ-897)
> UIREQ-897 correctly depend on babel-plugin-module-resolver

- CHANGELOG.md
- src/components/RequestsFilters/RequestsFiltersConfig.js
Change filtering by tags rules to allow for proper filter by tags behavior
Change filtering by tags rules from "\*EXPRESSION\*" to \*"EXPRESSION"\*
https://issues.folio.org/browse/UIREQ-904
> UIREQ-904: Change filtering by tags rules

- CHANGELOG.md
- src/ChooseRequestTypeDialog.test.js
- src/ItemsDialog.test.js
- src/components/ErrorModal/ErrorModal.js
- src/components/ErrorModal/ErrorModal.test.js
- src/components/RequestFormShortcutsWrapper/RequestsFormShortcutsWrapper.test.js
- src/components/RequestsFilters/RequestLevelFilter/RequestLevelFilter.test.js
- src/components/RequestsRouteShortcutsWrapper/RequestsRouteShortcutsWrapper.test.js
- src/components/ViewRequestShortcutsWrapper/ViewRequestShortcutsWrapper.test.js
- src/index.test.js
- src/routes/RequestsRoute.test.js
- Use camel case notation for all data-testid
- Remove magic strings for testIds and labelIds
https://issues.folio.org/browse/UIREQ-906
> UIREQ-906: Use camel case notation for all data-testid

- CHANGELOG.md
- src/routes/RequestsRoute.js
Replace moment.format() with moment.toISOString() because the
former does not guarantee the numbering system will be Latn (0-9,
Arabic numbers). 
[UIREQ-922](https://issues.folio.org/browse/UIREQ-922)
> UIREQ-922: Unexpected ugly UI error when placing request

- CHANGELOG.md
- src/ItemsDialog.js
Reassign limit variable from hardcoded value to MAX_RECORDS constant for ItemsDialog.js
https://issues.folio.org/browse/UIREQ-913
> UIREQ-913: Reassign limit variable from hardcoded value to MAX_RECORDS constant for ItemsDialog.js

- CHANGELOG.md
- src/routes/RequestsRoute.js
Reassign limit variable from hardcoded value to MAX_RECORDS constant for RequestsRoute.js
https://issues.folio.org/browse/UIREQ-914
> UIREQ-914: Reassign limit variable from hardcoded value to MAX_RECORDS constant for RequestsRoute.js

- CHANGELOG.md
- src/routes/RequestsRoute.js
Include call number (unselected by default) in Action menu.
Include service point name (unselected by default) in Action menu.
[UIREQ-899](https://issues.folio.org/browse/UIREQ-899)
[UIREQ-901](https://issues.folio.org/browse/UIREQ-901)
After merging this PR to UIREQ-898 branch, UIREQ-898 will be merged to master.
> UIREQ-899,UIREQ-900: Requests: Include call number and service point in Action menu list of fields to display

- CHANGELOG.md
- src/ItemsDialog.js
- src/ItemsDialog.test.js
Requests for Items on Instances with more than 10 holdings  do not allow a user to move a request to all requestable items
1. We add `limit: MAX_RECORDS` for get all data without this limit work BE limit. 
2. We use `for` for get all data because we use GET request
3. Increase code coverage.
https://issues.folio.org/browse/UIREQ-929
> UIREQ-929: Requests for Items on Instances with more than 10 holdings  do not allow a user to move a request to all requestable items

- CHANGELOG.md
- package.json
Update request-storage okapi interface to 6.0 version
https://issues.folio.org/browse/UIREQ-963
> UIREQ-963: Update request-storage okapi interface to 6.0 version

- CHANGELOG.md
- src/ItemsDialog.js
- src/ItemsDialog.test.js
When a user opens the request form to create or edit a request we can see a console error related to the missing param for `formatMessage`.
In our case, we had an unnecessary `ariaLabel` attribute which contains the result of execution of `formatMessage`.
Currently `MultiColumnList` component does not support `ariaLabel` property.
I have removed `ariaLabel` attribute which is unnecessary for `MultiColumnList` component and as a result I removed `formatMessage({ id: 'ui-requests.items.instanceItems' })` that does not contain the required `title` param.
[UIREQ-972](https://issues.folio.org/browse/UIREQ-972)
> UIREQ-972: Remove redundant ariaLabel prop

- CHANGELOG.md
- src/CancelRequestDialog.js
- src/CancelRequestDialog.test.js
- test/bigtest/tests/view-request-test.js
- test/jest/__mock__/intl.mock.js
- test/jest/__mock__/stripesComponents.mock.js
UI tests replacement with RTL/Jest for CancelRequestDialog.js
https://issues.folio.org/browse/UIREQ-876
> UIREQ-876: UI tests replacement with RTL/Jest for CancelRequestDialog.js

- CHANGELOG.md
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
- test/jest/__mock__/index.js
Jest/RTL tests cleanup of RequestsRoute.js file
- fix code style issues
- move listFormatter out of component
- cover `listFormatter` by jest/RTL tests
- cover `urls` by jest/RTL tests
[UIREQ-991](https://issues.folio.org/browse/UIREQ-991)
> UIREQ-991: Jest/RTL tests cleanup of RequestsRoute.js file

- CHANGELOG.md
- src/components/RequestInformation/RequestInformation.test.js
Improve code coverage of RequestInformation.js file
[UIREQ-951](https://issues.folio.org/browse/UIREQ-951)
> UIREQ-951: Cover RequestInformation by jest/RTL tests

- CHANGELOG.md
- package.json
- src/RequestForm.js
- src/RequestForm.test.js
- src/UserForm.js
- src/ViewRequest.js
- src/components/FulfilmentPreference/FulfilmentPreference.js
- src/components/FulfilmentPreference/FulfilmentPreference.test.js
- src/components/FulfilmentPreference/index.js
- src/components/RequestInformation/RequestInformation.js
- src/components/RequestInformation/RequestInformation.test.js
- src/components/RequesterInformation/RequesterInformation.js
- src/components/index.js
- src/constants.js
- src/utils.js
- src/utils.test.js
- test/jest/__mock__/finalFormComponents.mock.js
Add functionality to get service points that depend on the request type.
If the request type is selected - a dropdown with service points becomes visible and contains service points that allowed for the selected request type.
[UIREQ-977](https://issues.folio.org/browse/UIREQ-977)
> UIREQ-977: Ensure Only Available Service Points Display When Placing a New Request

- CHANGELOG.md
- src/components/RequestsFilters/RequestsFiltersConfig.js
- src/components/RequestsFilters/RequestsFiltersConfig.test.js
Correctly escape CQL special characters in tag API queries
https://issues.folio.org/browse/UIREQ-918
> UIREQ-918: Correctly escape CQL special characters in tag API queries

- CHANGELOG.md
- src/ChooseRequestTypeDialog.js
- src/ChooseRequestTypeDialog.test.js
- src/MoveRequestManager.js
- src/MoveRequestManager.test.js
- src/components/ComponentToPrint/ComponentToPrint.test.js
- src/constants.js
- src/utils.js
- src/utils.test.js
- translations/ui-requests/en.json
In the scope of the story, I had to get only available request types and show them inside the dropdown. If there are no available request types appropriate error should be shown.
Also, in the scope of this PR I have removed unused constants and functionality related to duplication request.
[UIREQ-1005](https://issues.folio.org/browse/UIREQ-1005)
> UIREQ-1005: Move request popup show available Request Types

- src/ChooseRequestTypeDialog.js
- src/ChooseRequestTypeDialog.test.js
- src/MoveRequestManager.js
- src/MoveRequestManager.test.js
- translations/ui-requests/en.json
Delete functionality that gets available request types for title. 
Only available request types for items should be retrieved from the server side.
Current PR is an improvement of https://github.com/folio-org/ui-requests/pull/1091
[UIREQ-1005](https://issues.folio.org/browse/UIREQ-1005)
> UIREQ-1005: Get request types for items only

- CHANGELOG.md
- src/components/InstanceInformation/InstanceInformation.js
- src/components/InstanceInformation/InstanceInformation.test.js
- src/components/ItemInformation/ItemInformation.js
- src/components/ItemInformation/ItemInformation.test.js
- src/components/RequestInformation/RequestInformation.js
- src/components/RequesterInformation/RequesterInformation.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/helpers/translationsProperties.js
Prefer @folio/stripes exports to private paths when importing components
https://issues.folio.org/browse/UIREQ-1020
> UIREQ-1020: Prefer @folio/stripes exports to private paths when importing components

- CHANGELOG.md
- src/MoveRequestManager.js
- src/RequestForm.js
- src/RequestForm.test.js
- src/constants.js
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
- Add "operation" parameter to "allowed-service-points" endpoint. 
- use "requestId" param instead of combination of "requesterId" and "itemId"/"instanceId" for request editing and moving
[UIREQ-1028](https://issues.folio.org/browse/UIREQ-1028)
> UIREQ-1028: Add "operation" parameter to "allowed-service-points" endpoint

- CHANGELOG.md
- src/MoveRequestManager.js
- src/MoveRequestManager.test.js
Server should be able to take information about selected item that will be used for moving request.
Add "itemId" parameter to the request url.
[UIREQ-1030](https://issues.folio.org/browse/UIREQ-1030)
> UIREQ-1030: Add "itemId" parameter to "allowed-service-points" endpoint

- CHANGELOG.md
- src/ItemDetail.js
- src/ItemDetail.test.js
- src/ViewRequest.js
- src/ViewRequest.test.js
- src/components/TitleInformation/TitleInformation.js
- src/components/TitleInformation/TitleInformation.test.js
- src/constants.js
- src/utils.js
- src/utils.test.js
Reshare DCB is a feature that allows sharing of assets within consortium.
Folio has primarily 3 roles in this feature - Lending, Borrowing, Pickup
**Lending Role**
Requested item would be a real item (i.e., an item from inventory).
Requester would be a virtual patron (user type - DCB)
**Borrowing Role**
Requested item would be a virtual item
Requester would be a real patron
**Pickup Role**
Requested item would be a virtual item (i.e., an item from inventory).
Requester would be a virtual patron (user type - DCB)
More details of the feature are available at https://wiki.folio.org/display/FOLIJET/DCB+Integration
1. Actions menu will display only "cancel request" menu item for all the roles explained above - hence the logic behind this implementation is a check if the request is virtual or …
> UIREQ-1032, UIREQ-1034, UIREQ-1035 - Request detail view update for Lending, Borrowing and Pickup DCB roles

- CHANGELOG.md
- src/ItemDetail.js
- src/ItemDetail.test.js
- src/ViewRequest.js
- src/ViewRequest.test.js
- src/components/TitleInformation/TitleInformation.js
- src/components/TitleInformation/TitleInformation.test.js
- src/constants.js
- src/utils.js
- src/utils.test.js
Reshare DCB is a feature that allows sharing of assets within consortium.
Folio has primarily 3 roles in this feature - Lending, Borrowing, Pickup
**Lending Role** 
- Requested item would be a real item (i.e., an item from inventory).
- Requester would be a virtual patron (user type - DCB)
**Borrowing Role** 
- Requested item would be a virtual item
- Requester would be a real patron
**Pickup Role** 
- Requested item would be a virtual item (i.e., an item from inventory).
- Requester would be a virtual patron (user type - DCB)
More details of the feature are available at https://wiki.folio.org/display/FOLIJET/DCB+Integration
1. Actions menu will display only "cancel request" menu item for all the roles explained above - hence the logic behind this implementation is a check if the request …
> UIREQ-1032, UIREQ-1034, UIREQ-1035 - Request detail view  update for Lending, Borrowing and Pickup DCB roles

- CHANGELOG.md
- package.json
- src/components/PrintContent/PrintContent.js
- src/components/PrintContent/PrintContent.test.js
- src/constants.js
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
- src/utils.js
- translations/ui-requests/en.json
Request Action - Create new option Print search slips
https://issues.folio.org/browse/UIREQ-1039
> UIREQ-1039: Request Action - Create new option Print search slips

- CHANGELOG.md
- src/ViewRequest.js
- src/ViewRequest.test.js
[UIREQ-1040](https://issues.folio.org/browse/UIREQ-1040) - [DCB] Request details: Hide Actions menu on closed request
Hide action menu when it is a DCB transaction - which means the request is involved with either virtual user or virtual item.
**Action menu hidden for "Closed-Filled" Request on Borrowing Library**
**Action menu hidden for "Closed-Filled" Request on Lending Library**
**Action menu hidden for "Closed-cancelled" Request on Lending Library**
- Do JIRAs exist to …
> UIREQ-1040 - Hide Actions menu on closed request of DCB Transaction

- CHANGELOG.md
- package.json
Add support for search-slips okapi interface version 0.1
https://issues.folio.org/browse/UIREQ-1042
Associated with https://github.com/folio-org/ui-requests/pull/1122
Should be merged after https://issues.folio.org/browse/CIRC-1933
> UIREQ-1042: Add support for search-slips okapi interface version 0.1

- CHANGELOG.md
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
Make updating of TLR settings when settings config is changed
[UIREQ-1063](https://folio-org.atlassian.net/browse/UIREQ-1063)
> UIREQ-1063: "Create title level request" option is still checked after disabling on settings page

- CHANGELOG.md
- src/ViewRequest.test.js
- src/constants.js
- src/routes/RequestQueueRoute.js
- src/routes/RequestsRoute.js
- src/utils.js
- src/utils.test.js
Use `settings/entries` endpoint instead of `configuration/entries` endpoint to get settings information.
[UIREQ-1062](https://folio-org.atlassian.net/browse/UIREQ-1062)
> UIREQ-1062: Use settings/entries endpoint to get settings information

- CHANGELOG.md
- package.json
- src/components/ComponentToPrint/ComponentToPrint.js
- src/components/ComponentToPrint/ComponentToPrint.test.js
- src/routes/RequestsRoute.js
Only certain HTML tags should be rendered when displaying staff slips
https://issues.folio.org/browse/UIREQ-1080
For resolve current problem we should use `DOMPurify.sanitize` confirmed with John
> UIREQ-1080: Only certain HTML tags should be rendered when displaying staff slips

- CHANGELOG.md
- src/RequestForm.js
- translations/ui-requests/en.json
https://folio-org.atlassian.net/browse/UIREQ-1073
We removed local `saveAndClose` label and replace it with `stripes-components.saveAndClose`. Also all related tests updated
> UIREQ-1073: Use Save & close button label stripes-component translation key

- src/components/ComponentToPrint/ComponentToPrint.js
- src/routes/RequestsRoute.js
Only certain HTML tags should be rendered when displaying staff slips. Add support for `Barcode `tag with sanitize.
https://issues.folio.org/browse/UIREQ-1080
For resolve current problem we should use `DOMPurify.sanitize` confirmed with John. Add support for Barcode tag with sanitize. Change log was already updated.
> UIREQ-1080: Add support for Barcode tag with sanitize

- CHANGELOG.md
- src/RequestForm.js
- src/components/RequestInformation/RequestInformation.js
- src/components/RequestInformation/RequestInformation.test.js
If a user has a default service point it should be automatically preselected as an initial value.
Initially we had always visible Fulfilment Preference field and after initial render of parent component all default values were set to appropriate fields.
But now Fulfilment Preference is not visible by default and it becomes visible only when user selects Request Type.
As a result I added method that set Fulfilment Preference default values to Request Type filed handler. 
[UIREQ-1095](https://folio-org.atlassian.net/browse/UIREQ-1095)
> UIREQ-1095: Pickup service point on an item request is not populated with the user's default pickup service point

- CHANGELOG.md
- src/ViewRequest.js
- src/ViewRequest.test.js
Hide Action menu on secondary requests (ECS + mod-tlr)
https://issues.folio.org/browse/UIREQ-1105
> UIREQ-1105: Hide Action menu on secondary requests (ECS + mod-tlr)

- package.json
[UIREQ-1121](https://folio-org.atlassian.net/browse/UIREQ-1121).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for …
> UIREQ-1121 - Add permissions to fetch "Enable Print Details(Pick Slips)" Settings (follow-up)

- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
[UIREQ-1119](https://folio-org.atlassian.net/browse/UIREQ-1119)
This follow-up PR is to address the reported [issue](https://folio-org.atlassian.net/browse/UIREQ-1119?focusedCommentId=226068) - "export search results to csv" when only Print Status filter is selected.
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> UIREQ-1119 - Export CSV on Print Status filter selection (follow-up)

- CHANGELOG.md
- src/RequestForm.js
- src/RequestForm.test.js
- src/utils.js
- src/utils.test.js
Fix issue with Proxy's patron group and delivery address that shown instead of Sponsor's when creating request
Use proxy patron group and delivery address if proxy selected. In other cases use data of selected user.
[UIREQ-1132](https://folio-org.atlassian.net/browse/UIREQ-1132)
[UIREQ-1133](https://folio-org.atlassian.net/browse/UIREQ-1133)
> UIREQ-1132, UIREQ-1133: Fix issue with Proxy's patron group and delivery address that shown instead of Sponsor's when creating request

- CHANGELOG.md
- package.json
[UIREQ-1137](https://folio-org.atlassian.net/browse/UIREQ-1137).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for …
> UIREQ-1137 - Add missing sub-permissions to fetch "pick-slips" and "search-slips" records in "Requests: View, edit, cancel" permission.

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
- src/routes/RequestsRoute.js
- Update permissions set to be able to get item/instance information
- Update version of `actions/upload-artifact` to v4 due to failed build
- Add `prevState` param that was accidentally removed during merging
Add `circulation.items-by-instance.get` sub-permission to `ui-requests.create` permission.
[UIREQ-1148](https://folio-org.atlassian.net/browse/UIREQ-1148)
> UIREQ-1148: Update permissions set to be able to get item/instance information

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
Update upload-artifact actions from v1 and v2 to v4
https://issues.folio.org/browse/UIREQ-1150
> UIREQ-1150: Update upload-artifact actions from v1 and v2 to v4

- CHANGELOG.md
- src/RequestForm.js
- src/RequestForm.test.js
- src/RequestFormContainer.js
- src/RequestFormContainer.test.js
- src/components/InstanceInformation/InstanceInformation.js
- src/components/InstanceInformation/InstanceInformation.test.js
- src/components/ItemInformation/ItemInformation.js
- src/components/ItemInformation/ItemInformation.test.js
- src/constants.js
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
In some cases when we create an Item level request we do not send `instanceId` param to the server.
In this PR I get `instanseId` param from item that was received from `circulation/items-by-instance`  endpoint.
[UIREQ-1149](https://folio-org.atlassian.net/browse/UIREQ-1149)
> UIREQ-1149: Use "instanceId" param for ILR from items response

- CHANGELOG.md
- package.json
- Add missed **"tlr.settings.get"** permission to get tlr settings.
- Remove duplicated permission.
[UIREQ-1169](https://folio-org.atlassian.net/browse/UIREQ-1169)
> UIREQ-1169: Add missed permission to get tlr settings

- CHANGELOG.md
- package.json
Add `mod-settings.entries.collection.get` permission to be able to get requests related settings if user has only requests related permissions.
[UIREQ-1177](https://folio-org.atlassian.net/browse/UIREQ-1177)
> UIREQ-1177: 

- CHANGELOG.md
- package.json
Update permission after mod-patron-blocks permission changes
https://issues.folio.org/browse/UIREQ-1201
> UIREQ-1201: Update permission after mod-patron-blocks permission changes

- CHANGELOG.md
- src/ChooseRequestTypeDialog.js
- src/ChooseRequestTypeDialog.test.js
- test/jest/__mock__/stripesComponents.mock.js
Increase code coverage for src/ChooseRequestTypeDialog.js by Jest/RTL tests
[UIREQ-1044](https://folio-org.atlassian.net/browse/UIREQ-1044)
> UIREQ-1044: Increase code coverage for src/ChooseRequestTypeDialog.js by Jest/RTL tests

- CHANGELOG.md
- src/constants.js
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
- translations/ui-requests/en.json
[UIREQ-1191](https://folio-org.atlassian.net/browse/UIREQ-1191) - Include Retrieval service point column in csv exports.
I think maximum coverage has been achieved.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> UIU-1191 - Include `Retrieval service point` column in csv exports.

- CHANGELOG.md
https://folio-org.atlassian.net/browse/UIREQ-1224
> UIREQ-1224: Update changelog after release

- CHANGELOG.md
- src/deprecated/routes/RequestsRoute/RequestsRoute.js
- src/deprecated/routes/RequestsRoute/RequestsRoute.test.js
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesUtils.mock.js
Use `exportToCsv` from `stripes-components` instead of a deprecated `exportCsv` from `stripes-utils`
[UIREQ-1138](https://folio-org.atlassian.net/browse/UIREQ-1138)
> UIREQ-1138 Change import of `exportToCsv` from `stripes-util` to `stripes-components`

- CHANGELOG.md
- src/deprecated/routes/RequestsRoute/RequestsRoute.js
- src/deprecated/routes/RequestsRoute/RequestsRoute.test.js
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
Fix accessibility issues related to clickable rows of requests list.
Instead of having the possibility to click on a row and see details page user should click on the link in a row (title).
[UIREQ-1231](https://folio-org.atlassian.net/browse/UIREQ-1231)
There is a code duplication because we have two different approaches that we use depending on feature flag.
In the scope of https://github.com/folio-org/ui-requests/pull/1235 feature flag and code inside "deprecated" folder will be removed.
> UIREQ-1231: Fix accessibility issues with requests list

- CHANGELOG.md
- src/ViewRequest.js
- src/ViewRequest.test.js
Hide edit, cancel, move and duplicate buttons for intermediate requests in central tenant.
[UIREQ-1254](https://folio-org.atlassian.net/browse/UIREQ-1254)
> UIREQ-1254: Hide edit, cancel, move and duplicate buttons for intermediate requests

- CHANGELOG.md
- src/ItemsDialog.js
- src/ItemsDialog.test.js
- src/deprecated/components/ItemsDialog/ItemsDialog.js
- src/deprecated/components/ItemsDialog/ItemsDialog.test.js
- src/deprecated/routes/RequestsRoute/RequestsRoute.js
- src/deprecated/routes/RequestsRoute/RequestsRoute.test.js
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
- src/views/components/ItemLink.js
- src/views/components/ItemLink.test.js
- src/views/components/RequesterLink.js
- src/views/components/RequesterLink.test.js
Use NoValue component for absent information.
[UIREQ-1262](https://folio-org.atlassian.net/browse/UIREQ-1262)
There is a code duplication in `deprecated` folder. That folder will be deleted later.
> UIREQ-1262: Implement support for fields without information in Requests UI

- CHANGELOG.md
- package.json
Add missed sub-permissions for "Requests: View" permission.
[UIREQ-1217](https://folio-org.atlassian.net/browse/UIREQ-1217)
> UIREQ-1217: Printing of request slips is unavailable with only "Requests: View" permission

- package.json
Follow up PR of https://github.com/folio-org/ui-requests/pull/1278
[UIREQ-1217](https://folio-org.atlassian.net/browse/UIREQ-1217)
> [FOLLOW UP] UIREQ-1217: Printing of request slips is unavailable with only "Requests: View" permission

- CHANGELOG.md
- package.json
- src/deprecated/routes/RequestsRoute/RequestsRoute.js
- src/deprecated/routes/RequestsRoute/RequestsRoute.test.js
- src/routes/RequestsRoute.js
- src/routes/RequestsRoute.test.js
- src/utils.js
- src/utils.test.js
Use  convertToSlipData and supporting functions
- In settings -> circulation -> staff slips we create template that contain token. When we try print this template in our modules checkin, requests, requests-mediated and etc we need match real data and token from template. For this match responsible convertToSlipData function and supporting functions. And in each of modules checkin, requests, requests-mediated and etc we have own exemplar of  convertToSlipData function and supporting functions. This mean that when we add new token in settings -> circulation -> staff slips we need updete convertToSlipData function in all modules checkin, requests, requests-mediated and etc. For resolve this problem we want move convertToSlipData function and supporting functions to one please and just reuse …
> UIREQ-1263: Use convertToSlipData and supporting functions from stripes-util

- CHANGELOG.md
- src/ItemDetail.js
Remove barcode hyperlink from the Central Tenant request Item information section
https://issues.folio.org/browse/UIREQ-1306
> UIREQ-1306: Remove barcode hyperlink from the Central Tenant request Item information section

- CHANGELOG.md
- src/ItemDetail.js
(As well as New Request page, which worked before and still does.)
All we're doing here is looking at the field that's been added to the request record's `item` subrecord in https://github.com/folio-org/mod-circulation/pull/1607 so that when we're viewing an existing request, we're able to show the loan-type. We also still look at the fields we checked before (`item.temporaryLoanType?.name` and `item.permanentLoanType?.name`), as these are still where the information shows up in the item record itself during the process of creating a new request.
> [UIREQ-1328] Display loan type on the Request Detail page
