CHANGELOG.md, Requests.js
Help clear console warnings as noted in [STRIPES-495](https://issues.folio.org/browse/STRIPES-495).
=> Include required clear-filter handlers. Refs STRIPES-495

CHANGELOG.md, ItemDetail.js, Requests.js, ViewRequest.js
Fixes [UIREQ-57](https://issues.folio.org/browse/UIREQ-57)
=> rewire links from items to inventory. Fixes UIREQ-57

CHANGELOG.md, package.json
Fixes [UIREQ-71](https://issues.folio.org/browse/UIREQ-71).
=> Upgrade query-string dependency. Fixes UIREQ-71.

CHANGELOG.md, ItemDetail.js, RequestForm.js, UserDetail.js, ViewRequest.js, package.json
Fixes [UIREQ-19](https://issues.folio.org/browse/UIREQ-19)
=> Lint. Fixes UIREQ-19

CHANGELOG.md, Requests.js, package.json
Refs [STSMACOM-64](https://issues.folio.org/browse/STSMACOM-64)
=> let SearchAndSort derive things from packageInfo. Refs STSMACOM-64

CHANGELOG.md, RequestForm.js, ViewRequest.js, package.json
Refs [UIREQ-80](https://issues.folio.org/browse/UIREQ-80)
=> prefer metadata over metaData. Refs UIREQ-80

CHANGELOG.md, RequestForm.js, package.json
https://issues.folio.org/browse/UIREQ-96
=> Fix input field value reference. Fixes UIREQ-96.

ItemDetail.js, RequestForm.js, Requests.js, ViewRequest.js
The code currently gets stripes from context when it is already available from props.
=> swap context.stripes for props.stripes

CancelRequestDialog.js, RequestForm.js, ViewRequest.js
https://issues.folio.org/browse/STCOR-208
`context.intl` isn't needed; switched to `props.intl`
=> STCOR-208 use intl on props, not context

package.json
Alphabetized and added the requirement for `cancellation-request-storage`
=> Add cancellation-reason-storage interface req

Requests.js, package.json
https://issues.folio.org/browse/UIREQ-102
=> UIREQ-102: Export search results to CSV

package.json
=> fix stripes-util version number

index.js
Bug fix for https://github.com/folio-org/ui-requests/pull/124
=> Fix malformed JSX

CHANGELOG.md, package.json
refs [STRIPES-555](https://issues.folio.org/browse/STRIPES-555)
=> update stripes-form to v1.0.0

RequestForm.js, package.json
https://issues.folio.org/browse/STCOM-331
=> STCOM-331 Get Pluggable from stripes-core

CHANGELOG.md, test/ui-testing/filters.js
Fixes [UIREQ-119](https://issues.folio.org/browse/UIREQ-119)
=> fix case-sensitive filter tests

CHANGELOG.md, package.json, src/ViewRequest.js, translations/ui-requests/en.json
https://issues.folio.org/browse/STRIPES-558
=> STRIPES-558 Remove notes helper app

CHANGELOG.md, package.json, src/CancelRequestDialog.js, src/ItemDetail.js, src/RequestForm.js, src/Requests.js, src/UserDetail.js, src/ViewRequest.js, src/utils.js
Uses new `@folio/stripes` package.
=> Use stripes 1.0

src/CancelRequestDialog.js, src/ItemDetail.js, src/RequestForm.js, src/Requests.js, src/UserDetail.js, src/ViewRequest.js, src/utils.js
Uses out-of-the-box `react-intl` constructs instead of functions consumed off the `stripes` god object.
=> STCOR-267 Use react-intl instead of stripes.intl

CHANGELOG.md, src/RequestForm.js, src/UserDetail.js, src/UserForm.js, src/ViewRequest.js
This PR introduces multiple changes to address UIREQ-124, UIREQ-132 and UIREQ-126.
=> Refactor requests app to address UIREQ-124, UIREQ-132 and UIREQ-126

translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json
=> Update translation strings as of 20181026T143111

CHANGELOG.md, src/RequestForm.js
Refs [STCOM-385](https://issues.folio.org/browse/STCOM-385)
=> show `active` column in find-user popup

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIREQ-106
=> Configure 'Requests: All permissions' permission set. Fixes UIREQ-106

CHANGELOG.md, src/Requests.js
https://issues.folio.org/browse/UIREQ-150
=> Show no requests by default. Fixes UIREQ-150.

translations/ui-requests/ar.json, translations/ui-requests/pt_BR.json
=> Update translation strings as of 20181110T181812

CHANGELOG.md, package.json
Support circulation v5.0, requiring service-point information on loans.
Refs [UIREQ-161](https://issues.folio.org/browse/UIREQ-161)
=> support circulation inteface v5

translations/ui-requests/ar.json
=> Update translation strings as of 20181112T151205

src/ItemDetail.js, src/RequestForm.js, src/Requests.js, src/UserDetail.js, src/UserForm.js, src/ViewRequest.js
This PR refactors request details view in order to load it faster. More details can be found in:
https://issues.folio.org/browse/UIREQ-134
=> Refactor opening request record. Part of UIREQ-134.

package.json
https://issues.folio.org/browse/UIREQ-106
=> Added missing permission. Part of UIREQ-106

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json
=> Update translation strings as of 20181128T202334

src/RequestForm.js, src/UserForm.js, src/ViewRequest.js
@zburke this PR refactors request form a bit more. I kept `on...` naming convention.
I introduced `onSelectProxy` to handle proxy selection independent from the user selection. The `onItemClick` and `onUserClick` handlers should be a bit cleaner now.
=> Cleanup request form. Part of UIREQ-146

CHANGELOG.md, package.json, src/RequestForm.js, src/Requests.js, src/ViewRequest.js, translations/ui-requests/en.json
https://issues.folio.org/browse/UIREQ-166
=> Add ability to duplicate request record. Part of UIREQ-166

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json
=> Update translation strings as of 20181228T143605

CHANGELOG.md, src/RequestForm.js
https://issues.folio.org/browse/UIIN-410
=> Fill item barcode if itemBarcode is present in the url. Part of UIIN-410.

CHANGELOG.md, src/Requests.js
Refs [STCOM-411](https://issues.folio.org/browse/STCOM-411)
=> move AppIcon import to @folio/stripes/core

.gitignore, src/RequestForm.js, test/bigtest/interactors/requests.js
I wish all form/navigation related issues were that simple...
=> Turn on navigation check on request form

test/ui-testing/test.js
What idiot removed new_request from test/ui-testing/ and forgot to
remove it from test/ui-testing/test.js? Seriously. Are people even
running these tests???
Refs [UIREQ-216](https://issues.folio.org/browse/UIREQ-216)
=> do not refer to removed test

CHANGELOG.md, src/RequestForm.js, src/ViewRequest.js
https://issues.folio.org/browse/UIREQ-192
=> Fix request expiration date not displaying on details view. Part of UIREQ-192

CHANGELOG.md, src/RequestForm.js, src/ViewRequest.js, src/constants.js
https://issues.folio.org/browse/UIREQ-206
=> Fix saving empty hold shelf expiration date. Fixes UIREQ-206

CHANGELOG.md, package.json, src/RequestForm.js
https://issues.folio.org/browse/UIREQ-214
=> Update circulation v7.0 and request-storage v3.0 OKAPI interfaces. Part of UIREQ-214

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190225T222207

CHANGELOG.md, src/RequestForm.js, src/Requests.js, test/bigtest/interactors/new-request.js, test/bigtest/tests/new-request-test.js, translations/ui-requests/en.json
Reorganize fields on request record to support conditional display of request types.
https://issues.folio.org/browse/UIREQ-208
=> Reorganize fields on request form. Part of UIREQ-208

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190227T140407

src/RequestForm.js, src/constants.js, test/bigtest/interactors/edit-request.js, test/bigtest/tests/edit-request-test.js, translations/ui-requests/en.json
Currently, Create/Edit screens have confusing prompts which should be changed
[Jira ticket](https://issues.folio.org/browse/UIREQ-217)
=> UIREQ-217: change confusing Create/Edit screen prompts

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190228T144944

CHANGELOG.md, src/RequestForm.js, src/Requests.js, src/constants.js, test/bigtest/interactors/new-request.js, test/bigtest/tests/new-request-test.js
To make selecting the correct type of request for the selected item easier for the user, we want to present only the requests types that are possible according to the white list. 
https://issues.folio.org/browse/UIREQ-209
=> Pre-filter request types based on whitelist. Part of UIREQ-209.

CHANGELOG.md, src/ItemDetail.js
https://issues.folio.org/browse/UIREQ-222
=> Fix item status. Fixes UIREQ-222

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190306T161944

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190312T134015

translations/ui-requests/it_IT.json
=> Update translation strings as of 20190313T213403

CHANGELOG.md, src/PatronBlockModal.js, src/RequestForm.js, translations/ui-requests/en.json
We are adding:
* Fix reasons when the patron has more than one block. Fix [UIU-804](https://issues.folio.org/browse/UIU-804).
* UX Consistency Fixes for Patron Blocks. Ref [UIU-902](https://issues.folio.org/browse/UIU-902).
=> Fixes fees/fines

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190321T130117

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190401T154238

src/PositionLink.js, src/RequestForm.js, src/ViewRequest.js
This PR refactors ViewRequest render to avoid double pane rendering. 
https://issues.folio.org/browse/UIREQ-231
=> Fix double detail pane view when clicking back. Part of UIREQ-231

src/CancelRequestDialog.js, src/PatronBlockModal.js, src/RequestForm.js, src/Requests.js, src/UserDetail.js, src/UserForm.js, src/ViewRequest.js, src/constants.js, src/utils.js
This PR fixes issues with unsaved changes modal. It also cleans up warnings related to react and stripes-components. 
https://issues.folio.org/browse/UIREQ-232
=> Cleanup requests module. Part of UIREQ-232

src/constants.js, test/bigtest/interactors/new-request.js, test/bigtest/tests/new-request-test.js
The previous PR missed `Recall` option for Paged item. This PR fixes it.
=> Fix Paged item. Part of UIREQ-247

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190425T181703

translations/ui-requests/es_ES.json
=> Update translation strings as of 20190429T154045

src/ItemDetail.js
The item object attached to request doesn't contain id.
https://issues.folio.org/browse/UIREQ-258
=> Fix item display. Part of UIREQ-258

src/RequestForm.js, src/UserDetail.js, src/ViewRequest.js, src/utils.js
https://issues.folio.org/browse/UIREQ-259
=> Fix requester patron group. Part of UIREQ-259

translations/ui-requests/ar.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190502T124851

src/ItemDetail.js, src/RequestForm.js, src/Requests.js, src/ViewRequest.js
This PR is a follow up on: https://github.com/folio-org/ui-requests/pull/335 which addresses couple more issues found by POs.
=> More work on requests without barcode. Part of UIREQ-253

translations/ui-requests/en_US.json
=> Update translation strings as of 20190503T205536

src/Requests.js
While working on UIREQ-253 I removed the ability to search by the barcode for no reason :(.
Big thank you to @zburke for noticing it. This PR should fix it.
=> Adding search by barcode back. Part of UIREQ-253

src/Requests.js, src/UserDetail.js, src/utils.js, test/bigtest/tests/view-request-test.js
https://issues.folio.org/browse/UIREQ-275
=> Fix request type during cloning. Part of UIREQ-275

translations/ui-requests/ar.json
=> Update translation strings as of 20190528T121921

src/Requests.js, src/constants.js, test/bigtest/interactors/requests.js, test/bigtest/network/config.js, test/bigtest/tests/all-requests-test.js, translations/ui-requests/en.json
Add the possibility to get hold expiration report.
=> UIREQ-273: Add the possibility to get hold expiration report.

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190603T125055

CHANGELOG.md, src/PatronBlockModal.js, src/RequestForm.js
We are adding:
* Fix system error caused patron with a block. Fix [UIU-1063](https://issues.folio.org/browse/UIU-1063).
=> Fix system error - Patron Block

translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json
=> Update translation strings as of 20190606T155546

translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190618T141239

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190627T152539

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190709T154346

CHANGELOG.md, src/UserForm.js
https://issues.folio.org/browse/UIREQ-291
=> Do not show proxy popup during edit. Fixes UIREQ-291.

CHANGELOG.md, src/UserForm.js
https://issues.folio.org/browse/UIREQ-290
=> Hide requester's proxy section when requesting as self. Fixes UIREQ-290.

src/RequestForm.js
To fix incorrect removing of holdShelfExpirationDate field from the model.
https://issues.folio.org/browse/UIREQ-297
=> UIREQ-297 - fixed incorrect removing of holdShelfExpirationDate

package.json, src/Requests.js, src/ViewRequest.js
- to add new permissions for requests module.
https://issues.folio.org/browse/UIREQ-107
https://issues.folio.org/browse/UIREQ-108
https://issues.folio.org/browse/UIREQ-109
=> UIREQ-107, UIREQ-108, UIREQ-109 - Added new permissions.

translations/ui-requests/ar.json
=> Update translation strings as of 20190807T131714

src/MoveRequestManager.js
https://issues.folio.org/browse/UIREQ-294
=> Allow type change when current type is prohibited by policy. Fixes UIREQ-294

CHANGELOG.md, src/ChooseRequestTypeDialog.js, src/MoveRequestManager.js, src/constants.js, src/utils.js, test/bigtest/interactors/view-request.js, test/bigtest/network/factories/holding.js, test/bigtest/network/factories/instance.js, test/bigtest/network/factories/request.js, test/bigtest/tests/move-request-test.js, translations/ui-requests/en.json
https://issues.folio.org/browse/UIREQ-303
=> Prevent move above page. Part of UIREQ-303

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20190819T080537

translations/ui-requests/pt_BR.json
=> Update translation strings as of 20190828T202658

src/Requests.js
The goal is to change the name of the sent parameter from 'Position' to 'position'.
=> UIREQ-330: Fix sorting by position

package.json
Fix "ui-requests.create" permission.
=> UIREQ-316: Fix "ui-requests.create" permission.

karma.conf.js, src/MoveRequestDialog.js, src/MoveRequestManager.js, src/Requests.js, test/bigtest/tests/view-request-test.js
A few things which made the tests fail:
1. The `isomorphic-fetch` was not mocked correctly by BigTest causing some tests to fail.
2. When two modals are present at the same time sometimes BigTest is loosing the reference to one for them for some reason (I'm not sure why this happens and it didn't before).
=> An attempt to fix requests tests

CHANGELOG.md, package.json, src/ViewRequest.js, src/index.js, src/routes/RequestQueueRoute.js, src/routes/urls.js, src/views/RequestQueueView.js, test/bigtest/network/config.js, test/bigtest/tests/request-queue-test.js
This PR connects work done in https://github.com/folio-org/ui-requests/pull/421 to the backend API.
https://issues.folio.org/browse/UIREQ-112
=> Connect to reorder queue API. Part of UIREQ-112

src/views/RequestQueueView.js, translations/ui-requests/en.json
This PR includes couple more changes to work done in https://github.com/folio-org/ui-requests/pull/421 Based on the feedback from PO.
https://issues.folio.org/browse/UIREQ-112
=> More changes based on feedback from PO. Part of UIREQ-112

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20191104T173556

translations/ui-requests/ar.json
=> Update translation strings as of 20191106T134035

src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-329
=> UIREQ-329: Add columnWidths for title.

CHANGELOG.md, src/ViewRequest.js, src/routes/RequestsRoute.js, test/bigtest/network/config.js, test/bigtest/network/factories/cancellationReason.js, test/bigtest/network/models/cancellationReason.js, test/bigtest/network/scenarios/default.js, test/bigtest/network/serializers/cancellationReason.js, test/bigtest/tests/view-request-test.js, translations/ui-requests/en.json
https://issues.folio.org/browse/UIREQ-364
=> Display cancellation reason on cancelled request. Part of UIREQ-364

translations/ui-requests/ar.json, translations/ui-requests/fr_FR.json
=> Update translation strings as of 20191118T154404

src/ViewRequest.js
https://issues.folio.org/browse/UIREQ-364
=> Adjust column width for cancellation info. Part of UIREQ-364

CHANGELOG.md, src/MoveRequestManager.js
https://issues.folio.org/browse/UIREQ-379
=> Remove 'Request can not be moved above page request' dialog. Part of UIREQ-379.

CHANGELOG.md, package.json, src/ViewRequest.js
https://issues.folio.org/browse/UIREQ-318
=> Provide reorder queue permission. Refs UIREQ-318

CHANGELOG.md, src/MoveRequestManager.js, src/ViewRequest.js, src/routes/RequestQueueRoute.js, src/views/RequestQueueView.js
https://issues.folio.org/browse/UIREQ-334
=> Show reorder view after moving request from one item to another. Part of UIREQ-334

package.json, src/components/ComponentToPrint/ComponenToPrint.js, src/components/ComponentToPrint/index.js, src/components/PrintButton/PrintButton.css, src/components/PrintButton/PrintButton.js, src/components/PrintButton/index.js, src/constants.js, src/routes/RequestsRoute.js, src/utils.js, test/bigtest/interactors/requests.js, test/bigtest/network/config.js, test/bigtest/network/factories/item.js, test/bigtest/network/factories/request.js, test/bigtest/tests/print-staff-slips-test.js, translations/ui-requests/en.json
Get all pick slips in the queue that are associated with current service point to print
https://issues.folio.org/browse/UIREQ-382
=> UIREQ-382 - FE: Print pick slips for service point on demand

src/ChooseRequestTypeDialog.js, src/MoveRequestDialog.js, src/MoveRequestManager.js, src/ViewRequest.js, src/components/Loading/DotSpinner.css, src/components/Loading/Loading.js, src/components/Loading/index.js, src/components/index.js, src/views/RequestQueueView.js
https://issues.folio.org/browse/UIREQ-334
=> Improve move performance. Part of UIREQ-334 

package.json, src/routes/RequestsRoute.js, src/utils.js, test/bigtest/network/config.js, test/bigtest/tests/print-staff-slips-test.js
Get all pick slips in the queue that are associated with current service point to print
https://issues.folio.org/browse/UIREQ-382
=> UIREQ-382 - Print pick slips for service point on demand

package.json
https://issues.folio.org/browse/UIREQ-389
=> Update move permission. Part of UIREQ-389

src/MoveRequestDialog.js, src/routes/RequestQueueRoute.js
https://issues.folio.org/browse/UIREQ-334
=> Show correct request after closing the request queue. Part of UIREQ-334

CHANGELOG.md, src/CancelRequestDialog.js
https://issues.folio.org/browse/UIREQ-321
=> UIREQ-321: Disable confirm button when cancel is in progress.

package.json
https://issues.folio.org/browse/UIREQ-389
=> UIREQ-389: Rename move and reorder permission

CHANGELOG.md, src/RequestForm.js, src/requests.css, test/bigtest/interactors/edit-request.js, test/bigtest/interactors/new-request.js, test/bigtest/tests/edit-request-test.js, test/bigtest/tests/new-request-test.js, translations/ui-requests/en.json
Move navigation buttons to to footer.
https://issues.folio.org/browse/UIREQ-370
https://github.com/folio-org/platform-core/pull/491
=> UIREQ-370 - Create/Edit a request | Move Save/Cancel buttons to the footer

src/RequestForm.js
Part of UIREQ-380. Fix bug of displaying delivery address when Fullfilment Preference is equal to Delivery in create/edit mode
https://issues.folio.org/browse/UIREQ-385
=> UIREQ-380: Fix displaying of delivery address

src/RequestForm.js
Part of UIREQ-385. Fix bug with displaying modal with validation error
https://issues.folio.org/browse/UIREQ-385?focusedCommentId=67330&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-67330
=> UIREQ-385: Fix form validation

translations/ui-requests/en_SE.json, translations/ui-requests/es_ES.json
=> Update translation strings as of 20191218T142024

CHANGELOG.md, src/RequestForm.js, src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-349
=> UIREQ-349: Fix links back to item record in new request form

CHANGELOG.md, src/RequestForm.js, src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-343
=> UIREQ-343: Fix open request count on item when creating a new request

translations/ui-requests/it_IT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20200109T152437

src/components/PrintButton/PrintButton.js, src/utils.js
- map new tokens
- fix page break for multiple items report
https://issues.folio.org/browse/UIREQ-406
=> UIREQ-406 - Pick-slips report printing issues

CHANGELOG.md, package.json, src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-399
=> UIREQ-399: Fix sorting by request date

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20200117T173544

CHANGELOG.md, package.json, src/constants.js, src/routes/RequestsRoute.js, src/utils.js, src/views/RequestQueueView.js, test/bigtest/network/config.js, test/bigtest/network/factories/item.js
... and related changes to item.status and copyNumber(s)
https://issues.folio.org/browse/UIREQ-405
=> UIREQ-405: Update okapi interfaces

CHANGELOG.md, src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-342
=> UIREQ-342: Fix sorting by proxy

CHANGELOG.md, src/components/RequestsFilters/RequestsFilters.js, src/components/RequestsFilters/RequestsFiltersConfig.js, src/components/RequestsFilters/index.js, src/constants.js, src/routes/RequestsRoute.js, test/bigtest/interactors/requests.js, translations/ui-requests/en.json
Add an ability to filter requests by tags.
https://issues.folio.org/browse/UIREQ-409
=> UIREQ-409 - Filter Requests by Tags

CHANGELOG.md, src/MoveRequestDialog.js, src/RequestForm.js, src/constants.js, src/utils.js, test/bigtest/interactors/error-modal.js, test/bigtest/network/factories/item.js, test/bigtest/tests/new-request-test.js, translations/ui-requests/en.json
https://issues.folio.org/browse/UIREQ-392
=> UIREQ-392: Prevent all request types for declared lost item

translations/ui-requests/it_IT.json
=> Update translation strings as of 20200127T201424

src/components/RequestsFilters/RequestsFilters.js
sort available tags in alphabetical order
https://issues.folio.org/browse/UIREQ-409
=> UIREQ-409 - added alphabetical order for list of available tags

CHANGELOG.md, src/RequestForm.js, src/requests.css, test/bigtest/interactors/edit-request.js, test/bigtest/interactors/new-request.js, test/bigtest/tests/edit-request-test.js, test/bigtest/tests/new-request-test.js, translations/ui-requests/en.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json
Backport the PRs related to UIREQ-370, Move Save/Cancel buttons to the footer, to the 2019-q4 branch (`b1.14-patch`) in preparation for a patch release. 
Refs [UIREQ-370](https://issues.folio.org/browse/UIREQ-370)
=> UIREQ-370 backport "Move Save/Cancel buttons to the footer" to v1.14

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/ur.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20200211T224145

CHANGELOG.md, src/RequestForm.js, src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-353
=> Only fetch open loans when loading an item. Fixes UIREQ-353

src/UserForm.js
https://issues.folio.org/browse/UIREQ-413
=>  UIREQ-413: Use correct requester and proxy name on user's form.

CHANGELOG.md, src/routes/RequestsRoute.js, src/utils.js, test/bigtest/network/config.js, test/bigtest/tests/utils-test.js
Add possible for render all available tokens on pick slip
https://issues.folio.org/browse/UICIRC-416
=> UICIRC-416 - add possible for render all available tokens on pick slip

src/utils.js, test/bigtest/tests/utils-test.js
Fix problems with localization for available tokens on pick slip
https://issues.folio.org/browse/UICIRC-416
=>  UICIRC-416 - fix problems with localization for available tokens on pick slip

CHANGELOG.md, src/UserDetail.js
https://issues.folio.org/browse/UIREQ-424
=> UIREQ-424: Fix link to ui-users from request details screen.

src/UserForm.js
https://issues.folio.org/browse/UIREQ-424
=> UIREQ-424: Fix link to users on request edit view

src/routes/RequestsRoute.js, src/utils.js
Allow user cancel new request after сlick on keep editing on previous cancelation.
https://issues.folio.org/browse/UIREQ-417
=> UIREQ-417 - New/Edit Request: Cancel and "X" does not work as expected once you click Keep editing

CHANGELOG.md, src/RequestForm.js
Restore shape of `selectedUser` object. 
Refs [UIREQ-426](https://issues.folio.org/browse/UIREQ-426), [UIREQ-442](https://issues.folio.org/browse/UIREQ-442)
=> UIREQ-426 restore change service point for open page request

CHANGELOG.md, src/ItemDetail.js, src/routes/RequestsRoute.js, test/bigtest/interactors/edit-request.js, test/bigtest/interactors/view-request.js, test/bigtest/network/factories/request.js, test/bigtest/tests/edit-request-test.js, test/bigtest/tests/view-request-test.js
Refs [UIREQ-433](https://issues.folio.org/browse/UIREQ-433)
=> UIREQ-433: Fix display of the request count on item (#537)

translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/fr.json, translations/ui-requests/he.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/ur.json
=> Update translation strings as of 20200409T134057

CHANGELOG.md, src/RequestForm.js, src/ViewRequest.js, src/asyncValidate.js, src/utils.js, test/bigtest/helpers/setup-application.js, test/bigtest/interactors/new-request.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/default.js, test/bigtest/tests/new-request-test.js
Add ability to create a request with the requester without barcode.
https://issues.folio.org/browse/UIREQ-444
=> UIREQ-444: Add ability to create a request with the requester without barcode

CHANGELOG.md, src/routes/RequestsRoute.js
This PR cleans up the export to CSV a bit.
https://issues.folio.org/browse/UIREQ-453
=> UIREQ-453: Fix export to CSV

CHANGELOG.md, src/routes/RequestsRoute.js
=> UIREQ-451 Restore block-details link to blocked-reason modal

CHANGELOG.md, src/RequestForm.js, src/constants.js, src/utils.js, test/bigtest/tests/new-request-test.js
Prevent requests for items with the status claimed returned.
https://issues.folio.org/browse/UIREQ-391
=> UIREQ-391: Prevent requests for items with the status claimed returned

translations/ui-requests/ru.json
=> Update translation strings as of 20200519T123842

CHANGELOG.md, package.json, src/PatronBlockModal.js, src/RequestForm.js, src/routes/RequestsRoute.js, test/bigtest/interactors/edit-request.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/automatedPatronBlocks.js, test/bigtest/tests/automated-patron-blocks-test.js
Add automated patron blocks support for requests.
https://issues.folio.org/browse/UIREQ-471
=> UIREQ-471 - Patron Blocks: Is there an automated patron block on requesting?

translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hu.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ur.json
=> Update translation strings as of 20200609T205925

CHANGELOG.md, translations/ui-requests/en.json
Refs [UIREQ-474](https://issues.folio.org/browse/UIREQ-474)
=> UIREQ-474 make permissions localizable

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/ur.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20200615T161518

translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/ru.json
=> Update translation strings as of 20200615T202100

CHANGELOG.md, src/ViewRequest.js, src/constants.js, src/index.js, src/routes/NoteCreateRoute.js, src/utils.js, test/bigtest/interactors/view-request.js, test/bigtest/tests/utils-test.js, test/bigtest/tests/view-request-test.js, translations/ui-requests/en.json
- Add `Staff notes` accordion to request details pane
- Add `New staff notes` page
[UIREQ-457](https://issues.folio.org/browse/UIREQ-457)
=> UIREQ-457: Add staff notes accordion to request details page

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/ur.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20200624T182544

CHANGELOG.md, src/RequestForm.js, translations/ui-requests/en.json
Problem: Item field should become highlighted in red and validation should display under reading "Please select an item and hit enter"
Refs [UIREQ-326](https://issues.folio.org/browse/UIREQ-326)
=> UIREQ-326 validate presence of selectedItem before save

src/routes/NoteCreateRoute.js
Fix translation after [PR](https://github.com/folio-org/ui-requests/pull/590)
=> UIREQ-457: Fix translation

translations/ui-requests/pt_BR.json, translations/ui-requests/ru.json
=> Update translation strings as of 20200701T150841

src/RequestForm.js, src/asyncValidate.js, translations/ui-requests/en.json
https://issues.folio.org/browse/UIREQ-477
This PR includes some cleanup around user lookup.
1. The UserForm won't wait for request preferences before rendering
2. Improved user async validation
3. Added loading indicator when additional data (proxies, request preferences) is being loaded after user lookup is performed.
=> UIREQ-477: Improve loading requester details

CHANGELOG.md, src/components/RequestsFilters/RequestsFiltersConfig.js
This should improve the performance a bit when filtering by request types.
https://issues.folio.org/browse/CIRC-807
=> CIRC-817: Use == for requestType filters

CHANGELOG.md, package.json
Permission error when creating requests with only one permission `Requests: View, create`
https://issues.folio.org/browse/UIREQ-486
=> UIREQ-486: Add permission

CHANGELOG.md, package.json, src/routes/RequestsRoute.js, test/bigtest/interactors/instance-list.js, test/bigtest/interactors/requests-interactor.js, test/bigtest/network/config.js, test/bigtest/tests/all-requests-test.js
https://issues.folio.org/browse/UIREQ-481
The value for sorting was taken from the column labels, which led to a dependence on the tenant's locale.
This PR fixed this by providing the changes that ensure that the sort value refers to the column name.
=> UIREQ-481: Fix ability to sort by Request Date column

CHANGELOG.md, src/ViewRequest.js, src/components/ReferredRecord/ReferredRecord.css, src/components/ReferredRecord/ReferredRecord.js, src/components/ReferredRecord/index.js, src/components/index.js, src/routes/NoteCreateRoute.js, src/routes/NoteViewRoute.js, test/bigtest/interactors/note-view.js, test/bigtest/interactors/referred-record.js, test/bigtest/network/factories/request.js, test/bigtest/tests/note-view-test.js, translations/ui-requests/en.json
- Add possibility to view all assigned notes
- Supporting [PR](https://github.com/folio-org/stripes-smart-components/pull/860)
[UIREQ-467](https://issues.folio.org/browse/UIREQ-467)
=> UIREQ-467: Request staff notes: View assigned notes

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/ur.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20200709T123052

translations/ui-requests/pt_BR.json, translations/ui-requests/ru.json
=> Update translation strings as of 20200710T132222

translations/ui-requests/fr_FR.json
=> Update translation strings as of 20200716T140311

CHANGELOG.md, src/index.js, src/routes/NoteEditRoute.js, src/routes/index.js, test/bigtest/interactors/note-edit.js, test/bigtest/interactors/note-view.js, test/bigtest/tests/note-edit-test.js, test/bigtest/tests/note-view-test.js
Implement edit note page 
[UIREQ-460](https://issues.folio.org/browse/UIREQ-460)
=> UIREQ-460: Request staff notes: Edit note details

CHANGELOG.md, src/components/LoadingButton/LoadingButton.js, src/components/LoadingButton/index.js, src/components/index.js, src/routes/RequestsRoute.js, translations/ui-requests/en.json
Add loading indicator when service point is switched and the pick slips are being reloaded.
https://issues.folio.org/browse/UIREQ-508
=> UIREQ-508: Add loading indicator when service point is switched

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/ur.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20200806T130626

translations/ui-requests/it_IT.json
=> Update translation strings as of 20200813T135432

translations/ui-requests/it_IT.json, translations/ui-requests/zh_CN.json
=> Update translation strings as of 20200827T215834

translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json
=> Update translation strings as of 20200901T173106

.gitignore, CHANGELOG.md, package.json, src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.js, src/components/RequestsFilters/PickupServicePointFilter/index.js, src/components/RequestsFilters/RequestsFilters.js, src/components/RequestsFilters/RequestsFiltersConfig.js, src/constants.js
purpose: https://issues.folio.org/browse/UIREQ-516
=> UIREQ-516 Create filter for Requests - Pickup service point

src/index.js
import react-router components correctly for v5.
=> react-router v5 cleanup

translations/ui-requests/ja.json
=> Update translation strings as of 20200914T140557

CHANGELOG.md, src/ItemDetail.js
https://issues.folio.org/browse/UIREQ-478
=> UIREQ-478 Implement easy way to copy Barcode in the Request record

CHANGELOG.md, src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.js, src/routes/RequestsRoute.js
purpose: https://issues.folio.org/browse/UIREQ-527
approach: replaced checkbox filter component with multiselect filter
=> UIREQ-527 Switch service point filter from checkboxes to multi-select picker

translations/ui-requests/ar.json
=> Update translation strings as of 20200930T202600

CHANGELOG.md, src/constants.js, translations/ui-requests/en.json
https://issues.folio.org/browse/UIREQ-531
Add Request Date to the Request CSV report.
=> UIREQ-531: Add Request Date to Request CSV report

translations/ui-requests/ar.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hi_IN.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/ko.json, translations/ui-requests/pl.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/ur.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20201007T133333

translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_US.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hi_IN.json, translations/ui-requests/ja.json, translations/ui-requests/ko.json, translations/ui-requests/pl.json, translations/ui-requests/pt_BR.json, translations/ui-requests/ur.json
=> Update translation strings as of 20201013T203429

translations/ui-requests/ar.json
=> Update translation strings as of 20201016T144229

translations/ui-requests/ar.json, translations/ui-requests/de.json
=> Update translation strings as of 20201020T221939

CHANGELOG.md, src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-540
=> UIREQ-540: Fix sorting by request status

translations/ui-requests/de.json, translations/ui-requests/ja.json
=> Update translation strings as of 20201102T140138

CHANGELOG.md, src/RequestForm.js
Fix default pickup service point when editing existing request
https://issues.folio.org/browse/UIREQ-544
=> UIREQ-544: Fix default pickup service point when editing existing request

src/RequestForm.js
Fix dependency from previous results of automated patron blocks request.
https://issues.folio.org/browse/UIREQ-545
=> UIREQ-545 - 'Phantom' automated patron block modal appearing after block has been cleared

translations/ui-requests/ar.json, translations/ui-requests/ber.json, translations/ui-requests/ca.json, translations/ui-requests/da.json, translations/ui-requests/de.json, translations/ui-requests/en_GB.json, translations/ui-requests/en_SE.json, translations/ui-requests/en_US.json, translations/ui-requests/es.json, translations/ui-requests/es_419.json, translations/ui-requests/es_ES.json, translations/ui-requests/fr.json, translations/ui-requests/fr_FR.json, translations/ui-requests/he.json, translations/ui-requests/hi_IN.json, translations/ui-requests/hu.json, translations/ui-requests/it_IT.json, translations/ui-requests/ja.json, translations/ui-requests/ko.json, translations/ui-requests/pl.json, translations/ui-requests/pt_BR.json, translations/ui-requests/pt_PT.json, translations/ui-requests/ru.json, translations/ui-requests/ur.json, translations/ui-requests/zh_CN.json, translations/ui-requests/zh_TW.json
=> Update translation strings as of 20201124T212804

src/RequestForm.js, src/constants.js, src/routes/RequestsRoute.js, src/utils.js
This PR fixes some additional issues found during review process in https://issues.folio.org/browse/UIREQ-553
The proxy and pickup service was not carried over correctly.
=> UIREQ-553: Show correct info on request form during duplicate

package.json
https://issues.folio.org/browse/UIREQ-573
=> UIREQ-573: Update to stripes v6

CHANGELOG.md, src/RequestForm.js, src/utils.js
Fix duplicating request when item is changed on the request form:
https://issues.folio.org/browse/UIREQ-572
=> UIREQ-572: Fix duplicating request when item is changed

CHANGELOG.md, package.json
Refs [UIREQ-578](https://issues.folio.org/browse/UIREQ-578)
=> UIREQ-578 increment stripes-cli to v2

CHANGELOG.md, src/routes/RequestsRoute.js
https://issues.folio.org/browse/UIREQ-596
=>  UIREQ-596: Increase limit for tags request to 10k

src/constants.js, src/routes/RequestQueueRoute.js, src/views/RequestQueueView.js, translations/ui-requests/en.json
Handle error when dedicated request queue page is out of sync
https://issues.folio.org/browse/UIREQ-373
=> UIREQ-373: Handle error when dedicated request queue page is out of sync

CHANGELOG.md, src/utils.js
Whoops; found one last unlocalized string.
Refs [UIREQ-220](https://issues.folio.org/browse/UIREQ-220)
=> UIREQ-220 localize Barcode

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIREQ-634
Increment stripes to v7, react to v17.
=> UIREQ-634: Increment stripes to v7, react to v17

CHANGELOG.md, src/components/TitleInformation/TitleInformation.js, src/components/TitleInformation/TitleInformation.test.js, src/components/TitleInformation/index.js, test/jest/__mock__/stripesComponents.mock.js, translations/ui-requests/en.json
Create reusable component for render title level information
We create reusable component for render title level information that will be used in future stories.
https://issues.folio.org/browse/UIREQ-654
=> UIREQ-654: Create reusable component for render title level information

CHANGELOG.md, package.json, src/RequestForm.js, src/ViewRequest.js, src/routes/RequestsRoute.js, test/bigtest/network/factories/request.js, test/bigtest/network/scenarios/default.js, test/bigtest/tests/new-request-test.js, test/bigtest/tests/note-view-test.js
TLR - data migration for request list, view, create, edit, duplicate.
https://issues.folio.org/browse/UIREQ-664
=> UIREQ-664: TLR - data migration part one

CHANGELOG.md, src/CancelRequestDialog.js, src/ItemsDialog.js, src/ItemsDialog.test.js, src/MoveRequestDialog.js, src/RequestForm.js, src/constants.js, src/views/RequestQueueView.js
TLR - data migration for dialogboxes and reorder list.
https://issues.folio.org/browse/UIREQ-665
=> UIREQ-665: TLR - data migration for dialogboxes and reorder list.

CHANGELOG.md, src/ItemDetail.js, src/RequestForm.js, src/ViewRequest.js, src/routes/RequestQueueRoute.js, src/views/RequestQueueView.js, test/bigtest/network/factories/request.js, test/bigtest/tests/note-view-test.js
TLR - data migration, move `holdingsRecordId`
https://issues.folio.org/browse/UIREQ-685
=> UIREQ-685: TLR - data migration part three

CHANGELOG.md, src/RequestForm.js
Turn an item level request into a title level request
https://issues.folio.org/browse/UIREQ-635
=> UIREQ-635: Turn an item level request into a title level request

CHANGELOG.md, package.json
After merging [this pull](https://github.com/folio-org/stripes-webpack/pull/43) request big tests are not working. Fix big tests.
Approach how to fix it was founded here https://github.com/folio-org/ui-requests/pull/832
https://issues.folio.org/browse/UIREQ-703
=> UIREQ-703: fix big tests

CHANGELOG.md, src/components/RequestsFilters/RequestLevelFilter/RequestLevelFilter.js, src/components/RequestsFilters/RequestLevelFilter/RequestLevelFilter.test.js, src/components/RequestsFilters/RequestLevelFilter/index.js, src/components/RequestsFilters/RequestsFilters.js, src/components/RequestsFilters/RequestsFiltersConfig.js, src/constants.js, src/routes/RequestsRoute.js, test/jest/__mock__/stripesComponents.mock.js, test/jest/__mock__/stripesSmartComponents.mock.js, translations/ui-requests/en.json
Create request level filter
https://issues.folio.org/browse/UIREQ-612
=> UIREQ-612: Create new request filter

CHANGELOG.md, src/PositionLink.js, src/RequestForm.js, src/ViewRequest.js, src/components/TitleInformation/TitleInformation.js, test/bigtest/network/factories/request.js, test/bigtest/tests/edit-request-test.js
Fix behavior of `hyperlinks` related to `TLR`
https://issues.folio.org/browse/UIREQ-702
=> UIREQ-702: Fix behavior of `hyperlinks` related to `TLR`

CHANGELOG.md, package.json
This should have been part of #802 but it was missed.
Refs [UIREQ-708](https://issues.folio.org/browse/UIREQ-708), [UIREQ-685](https://issues.folio.org/browse/UIREQ-685), [FOLIO-3376](https://issues.folio.org/browse/FOLIO-3376)
=> UIREQ-708 support request-storage 4.0

CHANGELOG.md, src/ItemsDialog.js, src/components/SortableList/SortableList.js, src/views/RequestQueueView.js, src/views/components/FulfillmentRequestsData.js, src/views/components/NotYetFilledRequestsData.js, src/views/components/NotYetFilledRequestsData.test.js, src/views/constants.js, test/bigtest/tests/request-queue-test.js
On Request queue page:
- Fulfillment in progress accordion should have position column.
- Open not yet filled accordion should have column with drag and drop icon.
https://issues.folio.org/browse/UIREQ-705
=> UIREQ-705: Fulfillment in progress accordion should have position column on Request queue page.

CHANGELOG.md, src/ItemDetail.js, src/RequestForm.js, src/ViewRequest.js
Fix the issue when link for item on edit page was broken
I also tried to refactor the code for better understanding.
https://issues.folio.org/browse/UIREQ-714
=> UIREQ-714: User is not redirected to "Item page"

CHANGELOG.md, src/routes/RequestsRoute.js, src/views/RequestQueueView.js, translations/ui-requests/en.json
Make translation keys more specific.
https://issues.folio.org/browse/UIREQ-715
=> UIREQ-715: Make translation keys more specific

CHANGELOG.md, src/ItemsDialog.js, src/RequestForm.js, src/RequestForm.test.js, src/ViewRequest.js, src/routes/RequestsRoute.test.js, src/views/RequestQueueView.js
Add id for Pane component.
https://issues.folio.org/browse/UIREQ-742
We create https://issues.folio.org/browse/UIREQ-745 for investigate problems with failed tests
=> UIREQ-742: Add id for Pane component

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md
- Add pull request template
https://issues.folio.org/browse/UIREQ-746
=> UIREQ-746: Add pull request template

CHANGELOG.md, package.json, src/RequestForm.js, translations/ui-requests/en.json
We need to add find-instance plugin on create request page for `title` level requests.
https://issues.folio.org/browse/UIREQ-675
=> UIREQ-675: Add title look-up to new request form

CHANGELOG.md, src/RequestForm.js, src/ViewRequest.js, src/routes/RequestsRoute.js, src/utils.js, test/bigtest/tests/edit-request-test.js, translations/ui-requests/en.json
Add success toast to Requests
https://issues.folio.org/browse/UIREQ-722
One test was skipped. We checked that the functionality covered by this test works fine. We think that test fails by timeout. Investigation of this problem was added at spike at the next sprint.
=> UIREQ-722: Add success toast to Requests

CHANGELOG.md, src/routes/RequestsRoute.js, translations/ui-requests/en.json
Add success toast to duplicated Requests
https://issues.folio.org/browse/UIREQ-747
=> UIREQ-747: Add success toast to duplicated Requests

CHANGELOG.md, src/PositionLink.js, translations/ui-requests/en.json
Change queue position message from "items" to "requests"
[UIREQ-755](https://issues.folio.org/browse/UIREQ-755)
BEFORE
AFTER
=> Change queue position message from "items" to "requests"

src/ItemsDialog.js, src/components/SortableList/SortableList.js
Clean up a few lint warnings. 
The exhaustive-deps warning, unfortunately, cannot be easily resolved :(
As noted in the comments, both the suggestions (adding deps, moving the 
functions inside this function) result in test failures. Maybe there's a 
weird/bad interaction between stripes-connect and hooks? It isn't clear.
=> lint. it does a body good.

CHANGELOG.md, src/PositionLink.js
Use all "open" filters for "view requests in queue" link
[UIREQ-756](https://issues.folio.org/browse/UIREQ-756)
After clicking on the link we will see that all "open" filters enabled
=> UIREQ-756 Use all "open" filters for "view requests in queue" link

CHANGELOG.md, src/ViewRequest.js, src/routes/RequestsRoute.js, src/utils.js, src/utils.test.js
Fix issue with success toast when user did not save first name
[UIREQ-753](https://issues.folio.org/browse/UIREQ-753)
BEFORE
AFTER
Success toast with first name and last name
Success toast with last name only 
Success toast with full name (including middle name)
=> UIREQ-753 fix notification issue with first name

CHANGELOG.md, package.json
Change changelog after module release
[https://issues.folio.org/browse/UIREQ-764](https://issues.folio.org/browse/UIREQ-764)
=> Change changelog after module release

CHANGELOG.md
Fix incorrectly changed changelog
[UIREQ-764](https://issues.folio.org/browse/UIREQ-764)
=> Fix incorrectly changed changelog

CHANGELOG.md, src/constants.js
Allow to choose request type for `Restricted` items.
https://issues.folio.org/browse/UIREQ-772
before:
after:
=> UIREQ-772: allows to choose request type for `Restricted` items

CHANGELOG.md, package.json, src/index.js
Remove react-hot-loader
https://issues.folio.org/browse/UIREQ-758
=> UIREQ-758: Remove react-hot-loader

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
Update NodeJS to v16 in GitHub Actions
https://issues.folio.org/browse/UIREQ-780
=> UIREQ-780: Update NodeJS to v16 in GitHub Actions

CHANGELOG.md, src/RequestForm.js, src/requests.css
Create/Edit Request: required is not read
For resolve this problem we add minimal changes in UI that was approved by PO
https://issues.folio.org/browse/UIREQ-775
=> UIREQ-775: Create/Edit Request: required is not read

CHANGELOG.md
Update changelog after module release
https://issues.folio.org/browse/UIREQ-796
=> UIREQ-796: Update changelog after module release

CHANGELOG.md, src/RequestForm.js
Add title to modal message for non requested status
https://issues.folio.org/browse/UIREQ-797
=> UIREQ-797: Add title to modal message for non requested status

CHANGELOG.md
[UIREQ-798](https://issues.folio.org/browse/UIREQ-798)
=> Modify changelog after release

CHANGELOG.md, src/CancelRequestDialog.js, src/RequestForm.js, src/utils.js, src/utils.test.js
Allow user to choose request type (page, hold, recall) when placing request
https://issues.folio.org/browse/UIREQ-815
=> UIREQ-815: Allow user to choose request type (page, hold, recall) when placing request

CHANGELOG.md
https://issues.folio.org/browse/UIREQ-816
=> UIREQ-816: Update changelog after release

CHANGELOG.md, src/RequestForm.js, src/routes/RequestsRoute.js, src/routes/RequestsRoute.test.js
When the user tries to create a request from Inventory item information is not loaded the first time. But when the user refreshes the page everything works as expected.
[UIREQ-834](https://issues.folio.org/browse/UIREQ-834)
=> UIREQ-834: TLR: Inconsistent title info loading when request created from Instance record

CHANGELOG.md
[UIREQ-848](https://issues.folio.org/browse/UIREQ-848)
=> UIREQ-848: Modify CHANGELOG after release

CHANGELOG.md, src/routes/RequestsRoute.js
Increased the limit for Service points in Request
https://issues.folio.org/browse/UIREQ-850
=> UIREQ-850: Increased the limit for Service points in Request

CHANGELOG.md, src/components/RequestsFilters/RequestsFiltersConfig.js
[UIREQ-846](https://issues.folio.org/browse/UIREQ-846)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to …
=> UIREQ-846: Cannot search for requests with tags ( or [

CHANGELOG.md, src/components/RequestsFilters/RequestsFilters.js, src/utils.js, src/utils.test.js, test/bigtest/interactors/view-request.js, test/bigtest/tests/utils-test.js
Populate the token "requester.preferredFirstName" in the pick slip, with the data provided by the backend in the ui-requests module
The changes in this PR require changes of https://github.com/folio-org/ui-circulation/pull/981
1. Updated requester.preferredFirstName for the pickslip in convertToSlipData utility function.
2. Updated unit test.
3. Fixed existing linting issues.
https://issues.folio.org/browse/UIREQ-809
https://issues.folio.org/secure/attachment/56250/preferred-firstname-token-pick-slip-.mp4
- What other modules …
=> UIREQ-809 - Populate the token 'requester.preferredFirstName' in the pick slip, with the data provided by the backend in the ui-requests module

CHANGELOG.md, src/components/ErrorModal/ErrorModal.js, src/components/ErrorModal/ErrorModal.test.js, src/components/ErrorModal/index.js, test/jest/__mock__/stripesComponents.mock.js
UI tests replacement with RTL/Jest
Tested for appearance, props->content display and an ability to call the close function.
https://issues.folio.org/browse/UIREQ-883
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIREQ-883: UI tests replacement with RTL/Jest for src/components/ErrorModal.js

CHANGELOG.md
R1 2023 Orchid module release 8.0.0
[UIREQ-903](https://issues.folio.org/browse/UIREQ-903)
=> UIREQ-903: R1 2023 Orchid module release 8.0.0

CHANGELOG.md, src/CancelRequestDialog.js, src/PatronBlockModal.js, src/RequestForm.js, src/UserForm.js
Made code improvements related to TLR functionality (remove comments, add constants).
[UIREQ-871](https://issues.folio.org/browse/UIREQ-871)
=> UIREQ-871: Investigate places for improvement for TLR

CHANGELOG.md, src/RequestForm.js
Fix the error with proxyUserId when it is not cleared correctly.
[UIREQ-919](https://issues.folio.org/browse/UIREQ-919)
=> UIREQ-919: Get an error when try to request Item

CHANGELOG.md, src/routes/urls.test.js
UI tests replacement with RTL/Jest for src/routes/urls.js
https://issues.folio.org/browse/UIREQ-896
=> UIREQ-896: UI tests replacement with RTL/Jest for src/routes/urls.js

CHANGELOG.md
[UIREQ-923](https://issues.folio.org/browse/UIREQ-923)
=> UIREQ-923: Update changelog after release

CHANGELOG.md
[UIREQ-925](https://issues.folio.org/browse/UIREQ-925)
=> UIREQ-925: R1 2023 Orchid Bug Fix module release 8.0.2

CHANGELOG.md, src/routes/RequestsRoute.js, translations/ui-requests/en.json
Include pickup service point in display of result list
[UIREQ-900](https://issues.folio.org/browse/UIREQ-900)
=> UIREQ-900: Requests: Include pickup service point in display of result list

CHANGELOG.md, src/routes/RequestsRoute.js, translations/ui-requests/en.json
Include "Effective call number string" in display of result list
[UIREQ-898](https://issues.folio.org/browse/UIREQ-898)
=> UIREQ-898: Requests: Include call number in display of result list

CHANGELOG.md, src/PositionLink.js, src/PositionLink.test.js
UI tests replacement with RTL/Jest for src/PositionLink.js
https://issues.folio.org/browse/UIREQ-879
=> UIREQ-879: UI tests replacement with RTL/Jest for src/PositionLink.js

CHANGELOG.md, src/RequestForm.js, src/components/ItemInformation/ItemInformation.js
Do not show validation error if item id is provided
[UIREQ-924](https://issues.folio.org/browse/UIREQ-924)
Tests will be implemented in the scope of the UIREQ-949
=> UIREQ-924: Cannot save item request from item with status On Order, because need a barcode

CHANGELOG.md, src/components/PrintButton/PrintButton.test.js, test/jest/__mock__/index.js, test/jest/__mock__/reactToPrint.mock.js
Cover `src/components/PrintButton/PrintButton.js` file by RTL/Jest tests.
[UIREQ-886](https://issues.folio.org/browse/UIREQ-886)
=> UIREQ-886: UI tests replacement with RTL/Jest for src/components/PrintButton/PrintButton.js

CHANGELOG.md, src/components/Loading/Loading.js, src/components/Loading/Loading.test.js, test/jest/__mock__/stripesComponents.mock.js
Cover `src/components/Loading/Loading.js` file by RTL/Jest tests.
[UIREQ-885](https://issues.folio.org/browse/UIREQ-885)
=> UIREQ-885: UI tests replacement with RTL/Jest for src/components/Loading/Loading.js

CHANGELOG.md, src/PatronBlockModal.test.js
Cover PatronBlockModal by RTL/Jest tests.
[UIREQ-878](https://issues.folio.org/browse/UIREQ-878)
=> UIREQ-878: UI tests replacement with RTL/Jest for src/PatronBlockModal.js

CHANGELOG.md, src/utils.js, src/utils.test.js, test/bigtest/tests/utils-test.js
Update staff slips to have the request date
add new token for request date
https://issues.folio.org/browse/UIREQ-962
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> UIREQ-962 added request.requestDate token

CHANGELOG.md, src/UserDetail.js, src/UserDetail.test.js
Cover UserDetail by RTL/Jest tests.
[UIREQ-881](https://issues.folio.org/browse/UIREQ-881)
=> UIREQ-881: UI tests replacement with RTL/Jest for src/UserDetail.js

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
https://issues.folio.org/browse/STRIPES-865
=> do not publish 'artifacts' to npm

CHANGELOG.md, src/components/SortableList/draggableRowFormatter.test.js
Create Jest/RTL test for draggableRowFormatter.js
Refs: [UIREQ-942](https://issues.folio.org/browse/UIREQ-942)
=> UREQ-942 Create Jest/RTL test for draggableRowFormatter.js

CHANGELOG.md, src/routes/RequestsRoute.js, src/routes/RequestsRoute.test.js, translations/ui-requests/en.json
TLRs check circulation rules before request is placed
https://issues.folio.org/browse/UIREQ-960
=> UIREQ-960: TLRs check circulation rules before request is placed.

CHANGELOG.md, src/components/LoadingButton/LoadingButton.test.js, src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.js, src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.test.js, src/routes/RequestQueueRoute.test.js, src/views/RequestQueueView.test.js, test/jest/__mock__/stripesComponents.mock.js
Jest/RTL tests cleanup
[UIREQ-988](https://issues.folio.org/browse/UIREQ-988)
=> UIREQ-988: Jest/RTL tests cleanup

CHANGELOG.md, src/components/PrintContent/PrintContent.js, src/components/PrintContent/PrintContent.test.js
Create Jest/RTL test for PrintContent.js
[UIREQ-935](https://issues.folio.org/browse/UIREQ-935)
=> UIREQ-935: Create Jest/RTL test for PrintContent.js

CHANGELOG.md, package.json, src/components/ErrorModal/ErrorModal.test.js, src/views/constants.test.js, test/jest/__mock__/intl.mock.js
Increase code coverage for Jest/RTL test
- Increase code coverage
- Add possible for run axe tests with example
https://issues.folio.org/browse/UIREQ-995
=> UIREQ-995: Increase code coverage for Jest/RTL tests

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
Update Node.js to v18 in GitHub Actions
https://issues.folio.org/browse/UIREQ-1000
=> UIREQ-1000: Update Node.js to v18 in GitHub Actions

CHANGELOG.md, src/components/ComponentToPrint/ComponentToPrint.test.js
UIREQ-931 create JEST/RTL test cases for ComponentToPrint.js
URL: https://issues.folio.org/browse/UIREQ-931
=> UIREQ-931 create JEST/RTL test cases for ComponentToPrint.js

CHANGELOG.md, src/routes/RequestsRoute.js, translations/ui-requests/en.json
Add new pickup service point error
https://issues.folio.org/browse/UIREQ-981
=> UIREQ-981: Add new pickup service point error

CHANGELOG.md, src/ChooseRequestTypeDialog.js, src/ChooseRequestTypeDialog.test.js, translations/ui-requests/en.json
Rename modal window for select request type
https://issues.folio.org/browse/UIREQ-1026
=> UIREQ-1026: Rename modal window for select request type

CHANGELOG.md, src/constants.js, src/routes/RequestsRoute.js, src/routes/RequestsRoute.test.js
Hit Enter or Search should move focus to the Results List pane header 
https://issues.folio.org/browse/UIREQ-564
=> UIREQ-564: Hit Enter or Search should move focus to the Results List pane header

CHANGELOG.md, src/components/RequestsFilters/RequestsFilters.js, src/components/RequestsFilters/RequestsFilters.test.js
Create Jest/RTL test for RequestsFilters.js
https://issues.folio.org/browse/UIREQ-937
=> UIREQ-937: Create Jest/RTL test for RequestsFilters.js

CHANGELOG.md, package.json
Use current optional dependencies
https://issues.folio.org/browse/UIREQ-1031
=> UIREQ-1031: Use current optional dependencies

CHANGELOG.md, package.json
Update circulation interface version to 14.2
https://issues.folio.org/browse/UIREQ-1038
=> UIREQ-1038: Update circulation interface version to 14.2

CHANGELOG.md
[UIREQ-1049](https://issues.folio.org/browse/UIREQ-1049)
=> UIREQ-1049: Update changelog after release

CHANGELOG.md, src/routes/RequestsRoute.js, src/routes/RequestsRoute.test.js, translations/ui-requests/en.json
Add page title to request list page
[UIREQ-1058](https://issues.folio.org/browse/UIREQ-1058)
=> UIREQ-1058: Add page title to request list page

CHANGELOG.md, src/routes/RequestsRoute.js
Error in Export Hold Shelf Clearance Report
https://issues.folio.org/browse/1057
=> UIREQ-1057: Error in Export Hold Shelf Clearance Report

CHANGELOG.md, src/components/RequestsFilters/RequestsFilters.test.js
Increase code coverage for src/components/RequestsFilters/RequestsFilters.js by Jest/RTL tests
[UIREQ-1051](https://folio-org.atlassian.net/browse/UIREQ-1051)
=> UIREQ-1051: Increase code coverage for src/components/RequestsFilters/RequestsFilters.js by Jest/RTL tests

CHANGELOG.md, src/RequestFormContainer.test.js
Increase code coverage of RequestFormContainer.js
[UIREQ-1045](https://folio-org.atlassian.net/browse/UIREQ-1045)
=> UIREQ-1045: Increase code coverage for src/RequestFormContainer.js by Jest/RTL tests

CHANGELOG.md, src/index.test.js
Increase code coverage for src/index.js by Jest/RTL tests
[UIREQ-1047](https://folio-org.atlassian.net/browse/UIREQ-1047)
=> UIREQ-1047: Increase code coverage for src/index.js by Jest/RTL tests

CHANGELOG.md, src/utils.js, src/utils.test.js
Add support for displaySummary token for Staff Slips
https://issues.folio.org/browse/UIREQ-1067
=> UIREQ-1067: Add support for displaySummary token for Staff Slips

CHANGELOG.md, package.json
Update changelog and package.json
[UIREQ-1076](https://folio-org.atlassian.net/browse/UIREQ-1076)
=> UIREQ-1076: Update changelog and package.json

CHANGELOG.md
Update CHANGELOG.md after release
https://issues.folio.org/browse/UIREQ-1086
=> UIREQ-1086: Update CHANGELOG.md after release

CHANGELOG.md, src/ViewRequest.js
Update visibility for actions  (ECS with mod-tlr enabled):
- Editing requests
- Cancelling request
- Reorder request queue
- Moving request
https://issues.folio.org/browse/UIREQ-1088
https://issues.folio.org/browse/UIREQ-1090
https://issues.folio.org/browse/UIREQ-1098
https://issues.folio.org/browse/UIREQ-1100
=> Requests app.: Moving request (ECS with mod-tlr enabled). Refs UIREQ-1100.

CHANGELOG.md, src/ViewRequest.js, src/ViewRequest.test.js, translations/ui-requests/en.json
Fix Request detail pane capitalization
https://issues.folio.org/browse/UIREQ-1106
=> UIREQ-1106: Fix Request detail pane capitalization

CHANGELOG.md, src/routes/RequestsRoute.js, translations/ui-requests/en.json
[UIREQ-1118](https://folio-org.atlassian.net/browse/UIREQ-1118) - Add "Printed" and "# Copies" columns in "Show Columns" list and Request records table.
Note: Displaying the data in these columns and test cases for these two columns will be covered in upcoming story - https://folio-org.atlassian.net/browse/UIREQ-1121
https://github.com/user-attachments/assets/7890075b-21a2-44c4-80e7-8b057a594695
- Are the JIRAs under active …
=> UIREQ-1118 - Add "Printed" and "# Copies" columns in "Show Columns" list and Request records table.

CHANGELOG.md, src/components/PrintButton/PrintButton.js, src/components/PrintButton/PrintButton.test.js, src/components/SinglePrintButtonForPickSlip/SinglePrintButtonForPickSlip.js, src/components/SinglePrintButtonForPickSlip/SinglePrintButtonForPickSlip.test.js, src/routes/RequestsRoute.js, src/routes/RequestsRoute.test.js, src/utils.js, src/utils.test.js
[UIREQ-1122](https://folio-org.atlassian.net/browse/UIREQ-1122) - Update printing details when printing pick slips in the Request app.
- The TODO mentioned in the current PR for Displaying the updated print details in #Copies and Printed Column in Request table upon 'Enable Print Log' Configuration will be covered in [UIREQ-1121](https://folio-org.atlassian.net/browse/UIREQ-1121).
- Test cases for getting the updated print details data in request table will also be covered in [UIREQ-1121](https://folio-org.atlassian.net/browse/UIREQ-1121).
- Single print.
- Print pick slips for [Service Point].
- Print selected pick slips for [Service Point].
https://github.com/user-attachments/assets/ae958c55-b5fe-4b8e-815a-295f92acfb98
Before merging this PR, please go through the following list and …
=> UIREQ-1122 - Update printing details when printing pick slips in the Request app

CHANGELOG.md, src/routes/RequestsRoute.js, src/utils.js, src/utils.test.js
UIREQ-1117 - Populate the token "request.barcodeImage" in the pick slip, with the data provided by the backend in the ui-requests module
UIREQ-1124 - Populate the token "staffUsername" in the pick slip, with the data provided by the backend in the ui-requests module
https://folio-org.atlassian.net/browse/UIREQ-1117
https://folio-org.atlassian.net/browse/UIREQ-1124
- Do PRs exist for these …
=> UIREQ-1117 - Populate the token 'request.barcodeImage' and 'staffUsername'  in the pick slip

package.json
[UIREQ-1121](https://folio-org.atlassian.net/browse/UIREQ-1121)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for …
=> UIREQ-1121 - Add missing permission to save Print Details" (follow-up)

CHANGELOG.md
[UIREQ-1135](https://folio-org.atlassian.net/browse/UIREQ-1135)
=> UIREQ-1135: Update changelog after release

CHANGELOG.md, src/components/RequestsFilters/RequestsFiltersConfig.js, src/constants.js, src/index.test.js, src/routes/RequestsRoute.js, src/routes/RequestsRoute.test.js, src/routes/utils.js, src/routes/utils.test.js, translations/ui-requests/en.json
[UIREQ-1140](https://folio-org.atlassian.net/browse/UIREQ-1140)
This PR introduces server-side sorting functionality for the 'Printed' and '# Copies' columns in the Requests table, aligning it with the existing sorting mechanism used for other columns.
https://github.com/user-attachments/assets/ce8f18f4-d0b7-40be-abe6-683e1d8da523
Ideally all of the PRs …
=> UIREQ-1140 - Add Sorting to 'Copies' and 'Printed' columns in Requests table

CHANGELOG.md, package.json
Also support okapiInterfaces inventory 14.0
https://issues.folio.org/browse/UIREQ-1160
=> UIREQ-1160: Also support okapiInterfaces inventory 14.0

CHANGELOG.md, src/routes/RequestsRoute.js
Send holdingsRecordId param for Item level request
[UIREQ-1167](https://folio-org.atlassian.net/browse/UIREQ-1167)
=> UIREQ-1167: Send holdingsRecordId param for ILR

CHANGELOG.md, package.json, src/ViewRequest.js, translations/ui-requests/en.json
Review and cleanup Module Descriptor
Permissions renamed in according with Permissions naming convention ( https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/156368925/Permissions+naming+convention )
https://issues.folio.org/browse/UIREQ-1156
=> UIREQ-1156: Review and cleanup Module Descriptor

CHANGELOG.md, package.json
Update ui-plugin-find-instances to version 8.0.0
https://issues.folio.org/browse/UIREQ-1172
=> UIREQ-1172: Update ui-plugin-find-instances to version 8.0.0

CHANGELOG.md, package.json
Release ui-requests v10.0.0 (Ramsons R2 2024)
https://issues.folio.org/browse/UIREQ-1165
=> Release v10.0.0

CHANGELOG.md, package.json, src/components/ComponentToPrint/ComponentToPrint.js, src/routes/RequestsRoute.js
Fix DOMPurify import
https://issues.folio.org/browse/UIREQ-1180
We have breaking changes in upcoming pull request
=> UIREQ-1180: Fix DOMPurify import

CHANGELOG.md
Update CHANGELOG.md after release
https://issues.folio.org/browse/UIREQ-1184
=> UIREQ-1184: Update CHANGELOG.md after release

CHANGELOG.md, src/RequestForm.js, src/RequestForm.test.js, src/RequestFormContainer.js, src/UserDetail.js, src/UserDetail.test.js, src/UserForm.js, src/UserForm.test.js, src/ViewRequest.js, src/components/RequesterInformation/RequesterInformation.js, src/components/RequesterInformation/RequesterInformation.test.js, src/constants.js, src/deprecated/components/RequestForm/RequestForm.js, src/deprecated/components/RequestForm/RequestForm.test.js, src/deprecated/utils.js, src/deprecated/utils.test.js, src/routes/RequestsRoute.js, src/routes/RequestsRoute.test.js, src/utils.js, src/utils.test.js
Hide Proxy functionality for ECS with mod-tlr enabled.
[UIREQ-1185](https://folio-org.atlassian.net/browse/UIREQ-1185)
=> UIREQ-1185: Hide Proxy functionality in Requests app. (ECS with mod-tlr enabled)

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIREQ-1194
https://github.com/folio-org/mod-circulation/pull/1508
- it will be merged after https://folio-org.atlassian.net/browse/CIRC-2139
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> [UIREQ-1194] - Update permissions for mod-circulation

CHANGELOG.md
[UIREQ-1176](https://folio-org.atlassian.net/browse/UIREQ-1176)
=> UIREQ-1176: Update changelog after release

CHANGELOG.md, package.json
Remove "circulation-bff-requests" okapi interface
[UIREQ-1203](https://folio-org.atlassian.net/browse/UIREQ-1203)
=> UIREQ-1203: Remove "circulation-bff-requests" okapi interface

CHANGELOG.md, package.json
[UIREQ-1204](https://folio-org.atlassian.net/browse/UIREQ-1204)
=> UIREQ-1204: Update changelog after release

CHANGELOG.md
https://folio-org.atlassian.net/browse/UIREQ-1210
=> UIREQ-1210: Update changelog after release

CHANGELOG.md, src/deprecated/routes/RequestsRoute/RequestsRoute.js, src/deprecated/routes/RequestsRoute/RequestsRoute.test.js
[UIREQ-1211](https://folio-org.atlassian.net/browse/UIREQ-1211) - Cleanup retrieval service point implementation from deprecated folder.
Couple of files from have been added to deprecated folder in the scope of PR https://github.com/folio-org/ui-requests/pull/1242/files. Those two files have been removed in this PR.
Ideally all of the PRs involved in …
=> UIREQ-1211 - Cleanup retrieval service point implementation from deprecated folder.

CHANGELOG.md, src/ViewRequest.test.js
Increase code coverage for src/ViewRequest.js by Jest/RTL tests
[UIREQ-1046](https://folio-org.atlassian.net/browse/UIREQ-1046)
=> UIREQ-1046: Increase code coverage for src/ViewRequest.js by Jest/RTL tests

CHANGELOG.md, src/ItemsDialog.js, src/components/FulfilmentPreference/FulfilmentPreference.js, src/components/PrintContent/PrintContent.js, src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.js, src/components/RequestsFilters/RequestLevelFilter/RequestLevelFilter.js, src/components/SortableList/SortableList.js, src/components/TitleInformation/TitleInformation.js
React v19: refactor away from default props for functional components
https://folio-org.atlassian.net/browse/UIREQ-1101
=> UIREQ-1101: React v19: refactor away from default props for functional components

CHANGELOG.md, src/deprecated/routes/RequestsRoute/RequestsRoute.js, src/routes/RequestsRoute.js
Add icons to requests action menu.
[UIREQ-1116](https://folio-org.atlassian.net/browse/UIREQ-1116)
New changes were added to "deprecated" folder as well. As a result there is a code duplication. 
"deprecated" folder will be removed very soon.
=> UIREQ-1116: Update Requests Actions menu

src/deprecated/routes/RequestsRoute/RequestsRoute.js, src/deprecated/routes/RequestsRoute/RequestsRoute.test.js, src/routes/RequestsRoute.js, src/routes/RequestsRoute.test.js, translations/ui-requests/en.json
Update action menu
[UIREQ-1116](https://folio-org.atlassian.net/browse/UIREQ-1116)
=> UIREQ-1116: Update action menu [FOLLOW UP PR]

CHANGELOG.md, src/deprecated/routes/RequestsRoute/RequestsRoute.js, src/routes/RequestsRoute.js
Add requests ID as a search parameter for search box
https://folio-org.atlassian.net/browse/UIREQ-1232
=> UIREQ-1232: Add requests ID as a search parameter for search box

CHANGELOG.md
https://folio-org.atlassian.net/browse/UIREQ-1260
=> UIREQ-1260: Update changelog after release

CHANGELOG.md, package.json
Add optionalOkapiInterfaces circulation-bff-loans 1.0
https://folio-org.atlassian.net/browse/UIREQ-1273
=> UIREQ-1273: Add optionalOkapiInterfaces circulation-bff-loans 1.0

CHANGELOG.md
[UIREQ-1271](https://folio-org.atlassian.net/browse/UIREQ-1271)
=> UIREQ-1271: Update changelog after release

CHANGELOG.md, src/constants.js, src/deprecated/routes/RequestsRoute/RequestsRoute.js, src/routes/RequestsRoute.js, translations/ui-requests/en.json
Add 'Request UUID' column to Requests data exported to CSV; https://folio-org.atlassian.net/browse/UIREQ-1264
=> UIREQ-1264: Requests App - Export Requests app search results list (csv) - Add Request UUID

CHANGELOG.md
[UIREQ-1277](https://folio-org.atlassian.net/browse/UIREQ-1277)
=> UIREQ-1277: Update changelog after release

CHANGELOG.md, package.json
Release v12.0.0
https://folio-org.atlassian.net/browse/UIREQ-1279
=> Release v12.0.0

CHANGELOG.md
https://issues.folio.org/browse/UIREQ-1288
=> UIREQ-1288: Update changelog after release

CHANGELOG.md, src/deprecated/components/RequestsFilters/RequestsFilters.js, src/deprecated/components/RequestsFilters/RequestsFilters.test.js, src/deprecated/components/RequestsFilters/RequestsFiltersConfig.js, src/deprecated/components/RequestsFilters/RequestsFiltersConfig.test.js, src/deprecated/routes/RequestsRoute/RequestsRoute.js, src/deprecated/routes/RequestsRoute/RequestsRoute.test.js, src/routes/RequestsRoute.js
Move related code to make the Retrieval SP filter enabled for ecs/non-ecs UI.
https://folio-org.atlassian.net/browse/UIREQ-1294
=> UIREQ-1294: [Retrieval SP filter] Move related code to make the filter enabled for ecs/non-ecs UI

CHANGELOG.md
[UIREQ-1300](https://folio-org.atlassian.net/browse/UIREQ-1300)
=> UIREQ-1300: Update changelog after release

CHANGELOG.md
Refs https://folio-org.atlassian.net/browse/UIREQ-1302
=> UIREQ-1302: Update CHANGELOG after release v12.0.2

CHANGELOG.md
https://folio-org.atlassian.net/browse/UIREQ-1308
=> UIREQ-1308: Update changelog after release
